### ISSUE TITLE
Faster with log()

### ISSUE THREAD

**Issue by joembedded** [kokke/tiny-AES-c#100]
Hi Kokke!

Thanks for this very smart and clean implementation!  One thing I would like to contribute is the optimisation of the multiplication. It costs 512 Bytes of temporoary RAM, but might speed up (only) the decoding significantly. On my ARM M3-Core ist speeds up factor 3-4 ;-) 
Below is what I added/canged.

Best regards, Jo

```c
...

#ifdef USE_DECRYPT_POWLOG
// Uses 512 Bytes of additional RAM, but is much faster than shifting.
// Because we work in GF(2^8), rules for Add  and Mul are defined.
// Mul can be replaced by adding the exponents in the log space
static uint8_t Multiply(uint8_t x, uint8_t y){
	if(x==0 || y==0) return 0; // x*0 is always 0
	return aes_ctx.pow[(aes_ctx.log[x]+aes_ctx.log[y]) % 255];
}
#else
// Much slower, but taked no extra RAM
static uint8_t Multiply(uint8_t x, uint8_t y){
  return (((y & 1) * x) ^
	   ((y>>1 & 1) * xtime(x)) ^
	   ((y>>2 & 1) * xtime(xtime(x))) ^
	   ((y>>3 & 1) * xtime(xtime(xtime(x)))) ^
	   ((y>>4 & 1) * xtime(xtime(xtime(xtime(x))))));
}
#endif
.....

void AES_init(const uint8_t* key){
#ifdef USE_DECRYPT_POWLOG
  uint16_t i;
  uint8_t x;
#endif
  KeyExpansion(aes_ctx.RoundKey, key);
  memset(aes_ctx.Iv,0,AES_BLOCKLEN);    // Initialize IV with 00000
#ifdef USE_DECRYPT_POWLOG
  for( i = 0, x = 1; i < 256; i++ ){
        aes_ctx.pow[i] = x;
        aes_ctx.log[x] = (uint8_t)i;
        x = ( x ^ xtime( x ) ) & 0xFF;
    }
#endif
}

...
```

**Comment by kokke** [comment]
Hi @joembedded and thanks a lot for the kind words :)

Factor 3-4 performance: das ist ja der Hammer! :+1: I am partly against exchanging resources for performance, as it is orthogonal to the primary design goal: low resource allocation.

However if it can be wrapped in a macro guard (`#ifdef ... #endif`), the user can make an informed choice, and that would be okay with me.

Can I see the full implementation somewhere? Couldn't find it in your repos.

**Comment by joembedded** [comment]
Hi Kokke,

yes, I also do not like allocating dead memory, but normally I work with (temporary) "Memory pools", that can be discarded in "one shot" (without garbage Collection), right after use...

But in this case, RAM is primarily a tradeof against ((precious) battery) energy: I use AES128-CBC in a (secure) bootloader. So Speed is much more important than RAM,..

There is a further Level of optimising the Code by using a 1024 Byte Cache for the AES-GF(2^8) multiplication. I have added a (complete) sample Project (RAD-Studio / TI's CCS).

Without Cache decompression requires 4800 msecs for a 5 MB file on my PC, With Cache only 750 msec. Feel free to check it by yourself or adding it to you Code/Repo (I will update my Repos in the next weeks...)

[m_aes.zip](https://github.com/kokke/tiny-AES-c/files/2028615/m_aes.zip)

***BTW:*** I am currently designing a completely new secure and Ultra-Low-Power IoT platform, based on the CC13xx/26xx-CPUs with On-Chip Radio, a (bootable) Serial-Flash-File-System and secure OTA-Firmware Updates over 2G/3G/LTE/Wifi/Uart/LocalRadio... 

Everything Looks VERY good until now and most of the Soft- and Hardware is already finished and tested. Data Transmission is highly compressed and the System is designed to work wirth an easy-2-copy PHP Framework on the Server, optimised for Minimum data volume.

It started as my personal Hobbyist-Project, but I see a VERY BIG Chance in the market, hence I have plans for this as a Commercial platform/product. Also, in the next months some new companies in Europe/Worldwide will start selling 100% "only M2M"-SIM-cards with (prepaid) 500 MB Data (valid for up to 10 years) (for Prices <10 EUR/500MB). Think of devices, that can get their latest Firmware automatically. For many years... 

_**Still I am looking for Partners for a Start-Up! I am living in the Southern of Germany (Karlsruhe) and if anybody is interested: -> Drop me a note ;-)**_

**Comment by DamonHD** [comment]
Sounds interesting.  Maybe this would be of interest to you:

http://www.earth.org.uk/IoT-Launchpad-research.html

We use a pure-software 8-bit AVR AES implementation developed during that in https://github.com/opentrv/OTAESGCM for our smart (IoT/ML) radiator valves.

Do get in touch if you'd like to chat!

Rgds

Damon

**Comment by joembedded** [comment]
Hi Damon,
thanks for the link. I have the Option to produce the Hardware in China at
a very low price. In the end I would like to use the CC13x2 from TI, which
has M4F-Core, 360kB Flash and 80kB RAM on chip as well as a 868Mhz Radio.
The System will only be a platform, only some "sample" end products, like a
bee hive weigh scale and a data logger will be supplied. Let's see what
happens... I'll docuemnt the Project on my page ( joembedded.de )...
With Kind regards,
Juergen (Jo)

2018-05-23 10:44 GMT+02:00 Damon Hart-Davis <notifications@github.com>:

**Comment by kokke** [comment]
Hi @joembedded and thanks for the kind offer :) I live about 2 hours north of Flensburg.

I work with embedded boards and ARMs alot, although mostly cortex M3s.
I will keep an eye on your website and see what you are up to. Your plans sound fun and interesting :+1: Are you planning to run the code in an RTOS or straight "on the metal" ?

If you want feedback on something, feel free to open an issue regardless of the subject - I'd gladly hear from you again :)

**Comment by joembedded** [comment]
Hi Damon,

yeah, I think the project is very ambicious. Most People do not understand my plans... So I am still looking for partners (and commercial interests are highly appreciated ;-)  )

However: My plan is clear. The bootloader runs on bare-metal-C (that makes it VERY portable and VERY small (it is alread in use and it is less the 8 kB on the CC1310!). And it does not rely on the AES-Features of the CC1310 (takes too much resources).

But for the User's Software, TI-RTOS is a very good choice, The toolchain is very convenient and FREE and the ARM- and MSP430- Compilers are really excelent. Nevertheless the user is free to use other toolchains too...

I have already built a Version 0,9 of the new module, named "LTrax" and in 8 days 8after ym Holidays) I'll start the layout of the first Release. I have attached 2 PDFs: My plans and the schematics.

And still: if anybody is interested: -> Drop me a note ;-)

[JesFsBootloader.pdf](https://github.com/kokke/tiny-AES-c/files/2064045/JesFsBootloader.pdf)
[ltrax_Draft.pdf](https://github.com/kokke/tiny-AES-c/files/2064046/ltrax_Draft.pdf)

**Comment by DamonHD** [comment]
Bare metal is not "ambitious", it's efficiency!  B^>  30 years ago I was writing a primitive 'RT'OS for Z80A, so there's no magic to me, just convenience, in an OS on unshared single-purpose h/w.

And we're busy on our bare-metal project right now!

Rgds

Damon
