### ISSUE TITLE
-Map linker flag prevents compilation

### ISSUE THREAD

**Issue by crawfordleeds** [kokke/tiny-AES-c#106]
When I run the make with the -Map,test.map linker flags (as is currently on master), I receive an error:
```
ld: unkown option: -Map
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [test.elf] Error 1
```

I was able to mitigate this issue by deleting `-Map,test.map` from the LDFLAGS. I have another project that utilizes the -Map linker flag with no issues so I'm not sure what the source of this issue is.

Is there value in keeping the -Map flag and if so, any suggestions on resolving the issue?

Great library, by the way. Thanks for putting this out into the world.

**Comment by kokke** [comment]
Hi @crawfordleeds and thanks for your interest in this project :)

The map-file is not necessary at all. I just like to have a map-file for debugging, so I put it in the Makefile way back :) It's safe to delete from the LDFLAGS anyway.

Thanks for the kind words :+1:
