### ISSUE TITLE
Error compiling for board generic esp8266 module

### ISSUE THREAD

**Issue by openact** [kokke/tiny-AES-c#107]
board version 2.4.1 esp8266
gets a error as 
"Error compiling for board generic esp8266 module"
ld return 1 exit status

undefined reference to AES_CBC_encrypt_buffer(AES_ctx*, unsigned char *, unsigned int)

**Comment by kokke** [comment]
Hi @openact 

I need more information from you if you want me to help.
For instance, how are you compiling the code? Which files exists and which commands are you running.

There is something wrong with the way you compile the code.
From the error message it looks like you are not linking the code in `aes.c` with the file that contains the main-function.

**Comment by openact** [comment]
i was using it in arduino ide..
included aes.h
defined
struct AES_ctx ctx 
char buffer[16]
length = 16
 then used void AES_init_ctx_iv(struct AES_ctx* ctx, const uint8_t* key, const uint8_t* iv); 
void AES_CBC_encrypt_buffer(struct AES_ctx* ctx, uint8_t* buf, uint32_t length);
these functions in loop section.

**Comment by kokke** [comment]
Hi @openact 

The reason seems to be as I expected: you are not linking against `aes.c`.

See this issue for another guy's explanation of how to compile in Arduino IDE:
https://github.com/kokke/tiny-AES-c/issues/68

You can also just copy/paste the contents of aes.c into the file that contains the main-function.

**Comment by kokke** [comment]
You have a file containing your main-function (let's say it's called `main.c`).
In `main.c` you `#include "aes.h"` which contains definitions of functions that reside in `aes.c`.
Therefore you need to include `aes.c` in the build or at least copy the contents into `main.c` or else the linker will complain of functions that are declared but not defined.

**Comment by openact** [comment]
ok.. thanks for pointing in the right direction.!

**Comment by openact** [comment]
@kokke working perfect now.. :thumbsup:

**Comment by bilogic** [comment]
> You have a file containing your main-function (let's say it's called `main.c`).
> In `main.c` you `#include "aes.h"` which contains definitions of functions that reside in `aes.c`.
> Therefore you need to include `aes.c` in the build or at least copy the contents into `main.c` or else the linker will complain of functions that are declared but not defined.

I'm using platformio, could you share how I can include ```aes.c``` in the build? I did not have to do this for other libraries, adding ```#include "header.h"``` was sufficient. Thank you.

**Comment by bilogic** [comment]
I found a workaround/solution, if I rename ```aes.c``` as ```aes.cpp```, I can compile with no issues.
