### ISSUE TITLE
test.c:test_encrypt_ecb_verbose() buf and buf2 unused

### ISSUE THREAD

**Issue by franzinc** [kokke/tiny-AES-c#108]
Unless I'm misreading the example, the code on lines [72](https://github.com/kokke/tiny-AES-c/blob/master/test.c#L72), 82 and 83 is not used anywhere and not needed for the example.

**Comment by franzinc** [comment]
I submitted a pull request to fix this.

**Comment by kokke** [comment]
Hi @franzinc - thanks for noticing!

I haven't paid much attention to the test script to be honest. I've done a lot of testing on the side, when using the library in applications.

I have checked out your changes, and I really like them. Thank you very much for that, and apologies for the late answer.

**Comment by kokke** [comment]
I have merged your PR #109 - once again :+1: thank you very much for your contribution.
