### ISSUE TITLE
InvMixColumns makes decryption time terrible

### ISSUE THREAD

**Issue by SilvaBruno0804** [kokke/tiny-AES-c#110]
The InvMixColumns step makes the code takes up to 10 times more time to decrypt than to encrypt in bigger sizes of plain text

**Comment by kokke** [comment]
Hi @SilvaBruno0804 - thanks for your feedback :+1: 

Yes this library is pretty slow in general. A lot of speed has been sacrificed for the sake of small binary size. If you need more speed, you should look a optimizing this library or consider using something completely else.

Speed is not a big priority for this project, and likely never will be. If you have an improvement, feel free to make a PR. I am always willing to review request for changes, as long as they don't increase the binary size considerably.

I will close this issue. Do feel free to keep commenting if you have further to add(?) :)
