### ISSUE TITLE
static compilation?

### ISSUE THREAD

**Issue by sam0x17** [kokke/tiny-AES-c#114]
Is there a way to compile this statically so I can get an `aes.a` file that I can statically link against?

**Comment by kokke** [comment]
Hi @sam0x17 - sure there is :) How, depends on your compiler/build environment.

If you are using gcc, you can run `ar rcs aes.a aes.o` and that will create the library/archive `aes.a` from `aes.o`, which you can then link against.

I can add a build-target that does this, to the Makefile if you want ?

**Comment by sam0x17** [comment]
that would be awesome if you did, great trick didn't know that!

**Comment by kokke** [comment]
Hi @sam0x17 

I've added a new build target to the Makefile : `make lib` .
This target creates `aes.a` which is a static library you can link against.

Example of how it can be used:

```
> /tmp/tiny-AES-c-master$ make clean
> /tmp/tiny-AES-c-master$ make lib
[CC] aes.o -Wall -Os -c
[AR] aes.a
> /tmp/tiny-AES-c-master$ gcc test.c aes.a
> /tmp/tiny-AES-c-master$ ./a.out

Testing AES128

CBC encrypt: SUCCESS!
CBC decrypt: SUCCESS!
CTR encrypt: SUCCESS!
CTR decrypt: SUCCESS!
ECB decrypt: SUCCESS!
ECB encrypt: SUCCESS!
ECB encrypt verbose:

plain text:
6bc1bee22e409f96e93d7e117393172a
ae2d8a571e03ac9c9eb76fac45af8e51
30c81c46a35ce411e5fbc1191a0a52ef
f69f2445df4f9b17ad2b417be66c3710

key:
2b7e151628aed2a6abf7158809cf4f3c

ciphertext:
3ad77bb40d7a3660a89ecaf32466ef97
f5d3d58503b9699de785895a96fdbaaf
43b1cd7f598ece23881b00e3ed030688
7b0c785e27e8ad3f8223207104725dd4

```

**Comment by sam0x17** [comment]
:+1: thanks so much!
