### ISSUE TITLE
Tests for AES256 fails

### ISSUE THREAD

**Issue by AHSauge** [kokke/tiny-AES-c#117]
I was trying out AES256 CRT the other day and discovered that it fails the tests. It also seems to fail the test cases described in NIST Special Publication 800-38A. 

Minimum code to reproduce:
```
	unsigned char AES_KEY[] = {
			0x60, 0x3d, 0xeb, 0x10, 0x15, 0xca, 0x71, 0xbe,
			0x2b, 0x73, 0xae, 0xf0, 0x85, 0x7d, 0x77, 0x81,
			0x1f, 0x35, 0x2c, 0x07, 0x3b, 0x61, 0x08, 0xd7,
			0x2d, 0x98, 0x10, 0xa3, 0x09, 0x14, 0xdf, 0xf4};

	unsigned char IV1[] = {
			0xf0, 0xf1, 0xf2, 0xf3, 0xf4, 0xf5, 0xf6, 0xf7,
			0xf8, 0xf9, 0xfa, 0xfb, 0xfc, 0xfd, 0xfe, 0xff };

	const unsigned char Case1[] = {
			0x6b, 0xc1, 0xbe, 0xe2, 0x2e, 0x40, 0x9f, 0x96,
			0xe9, 0x3d, 0x7e, 0x11, 0x73, 0x93, 0x17, 0x2a };

	const unsigned char Expected1[] = {
			0x60, 0x1e, 0xc3, 0x13, 0x77, 0x57, 0x89, 0xa5,
			0xb7, 0xa7, 0xf5, 0x04, 0xbb, 0xf3, 0xd2, 0x28 };

	struct AES_ctx ctx;
	AES_init_ctx_iv(&ctx, AES_KEY, IV1);
	AES_CTR_xcrypt_buffer(&ctx, Case1, sizeof(Case1));
	//Case1 should now be equal to Expected1, but it isn't
```
The above code is the first test case in "F.5.5 CTR-AES256.Encrypt" gotten from NIST Special Publication 800-38A

**Comment by monolifed** [comment]
AES_CTR_xcrypt_buffer does inplace encryption/decryption, so Case1 shouldn't be const. It might be the issue. I tried it (with my own fork which is more or less the same) and it worked i.e. Case1-after-AES_CTR_xcrypt_buffer is Expected1.

**Comment by AHSauge** [comment]
Sorry about that, the Case1 array is of course not be const. In my code where I'm testing it there is a memcpy into a buffer which I didn't add. I unfortunately neglected to remove the const when I made the code smaller.
Anyway, I've spotted my mistake. AES256 wasn't properly defined when I built the code which of course is a bit of a problem... Now it works fine.
