### ISSUE TITLE
test.c fails for AES256

### ISSUE THREAD

**Issue by g-aaroncruz** [kokke/tiny-AES-c#122]
Hi all,

After adding the following symbol `#define AES256 1` into the test.c file provided before the `#include "aes.h"` results in failures for all test cases. 

Below you should be able to see the output.

I ran this on an Ubuntu 18.04 machine with gcc version 7.3.0 (Ubuntu 7.3.0-27ubuntu1~18.04).

![image](https://user-images.githubusercontent.com/10556148/51356968-e9f4a480-1a79-11e9-8c16-560ba90f9710.png)

**Comment by kokke** [comment]
Hi @g-aaroncruz and thanks for your interest in this project.

You should not #define AES256 in the test-file, the makefile tests both AES128, AES192 and AES256.

If you want to permanently use AES256, you must define it in aes.h, not the test-driver.

**Comment by kokke** [comment]
This issue: https://github.com/kokke/tiny-AES-c/issues/119 is basically another guy experiencing the same problem. 

In there, I explain the reason why this fails in a bit more detail.
