### ISSUE TITLE
how create a 256 bit key

### ISSUE THREAD

**Issue by danieagle** [kokke/tiny-AES-c#127]
Hi!
How I can automatically create keys of 256bits ? 
Can suggest someone lib?

Very Very Very Thanks! :-)
and Thanks for this Wonderful lib.

[]'s Dani. :-)

**Comment by kokke** [comment]
Hi @danieagle and thank you for the kind words :)

I'm not 100% sure what you mean by automatically creating 256bit keys.

You could create the keys from random data, given that the random-generator is cryptographically secure.
You could also use a standard [Key Derivation Function](https://en.wikipedia.org/wiki/Key_derivation_function).

AES is a symmetric algorithm, meaning that it assumes a pre-shared secret, i.e. that the two parties have already agreed on an AES key before beginning encrypted communications.

If you want to generate a new AES key for each session, perhaps you could look into the [Diffie-Hellman key exchange](https://en.wikipedia.org/wiki/Diffie–Hellman_key_exchange) or alternatively the [Elliptic-Curve Diffie-Hellman key agreement algorithm](https://en.wikipedia.org/wiki/Elliptic-curve_Diffie%E2%80%93Hellman).

I have written a library implementing ECDH. You could try playing around a bit with that: https://github.com/kokke/tiny-ECDH-c

**Comment by danieagle** [comment]
Hi!
I need create 256bit keys from random data. :-)
Please(!) any c code ?

obs.: all symetrics keys will be encrypt with a asymetric algorithm, then I need just
the random stuff for symmetric keys. :-)

Very Very Very Thanks!
[]'s Dani.

**Comment by kokke** [comment]
https://github.com/kokke/tiny-AES-c/blob/master/test.c demonstrates how to use 256bit keys (along with 128 and 192 bit keys as well).

How do you intend to create the random data? Be advised that you use a cryptographically secure entropy source for this.
