### ISSUE TITLE
Use strings as keys and input

### ISSUE THREAD

**Issue by thomasxd24** [kokke/tiny-AES-c#131]
Hi, i was looking at the demo.c and i would like to implement it to an aes-254-ctr encryption
But it seems that the variables are in uint8 and hex and that its not ascii codes, so how can i use it in strings?
Also is there a way to avoid using iv? Or is it safe to use a random one?

Thanks!

**Comment by kokke** [comment]
Hi @thomasxd24 

> i would like to implement it to an aes-254-ctr encryption

You mean AES-256-CTR right? That configuration is supported yes.


>But it seems that the variables are in uint8 and hex and that its not ascii codes, 
>so how can i use it in strings?

All data is held in raw byte-arrays (uint8_t-arrays) and not in the ASCII text format, yes.
From my experience as a C developer, this is the case way more often than not.
(`uint8_t` is just another way of saying an unsigned 8-bit integer -- which is usually an alias for `unsigned char`).

Converting raw byte-arrays to/from hex-strings is a common C question on stackoverflow.com:

https://stackoverflow.com/questions/6357031/how-do-you-convert-a-byte-array-to-a-hexadecimal-string-in-c
https://stackoverflow.com/questions/3408706/hexadecimal-string-to-byte-array-in-c



>Also is there a way to avoid using iv? Or is it safe to use a random one?

Yes, by using ECB-mode, but I would recommend against using that mode of operation, unless you know exactly what trade-off you are making there. 

The IV is not a secret and is just meant for adding extra initial entropy/randomness.
You can generate an IV at random and send it in clear-text to the other party, no problem :)
