### ISSUE TITLE
C++ version

### ISSUE THREAD

**Issue by ifknot** [kokke/tiny-AES-c#135]
Hi thanks for inspiration very readable & has sent me learning more about Rijndael and trying a C++17 implementation as a template class (obviously more to do) https://github.com/ifknot/AES-C-17

**Comment by kokke** [comment]
Hi @ifknot and thanks for the kind words :)

Just for fun, have you tried comparing binary sizes and runtimes between the C version and the C++ ones?

**Comment by ifknot** [comment]
Hi @kokke as requested performance comparisons are on the [AES-C++17 front page](https://github.com/ifknot/AES-CPP17) the R script and raw data are in the stats directory - there a few low hanging fruit optimization as well as the AES-NI extensions to the x86 instruction set architecture - so yes, as you says, this is just for fun :)
But.. can you pls help with how I can best go about comparing binary sizes?
Ta
