### ISSUE TITLE
Encryption made using "TinyAES" library for AES 256 using CTR and CBC mode does not match with the encryption made using the python library "PyCrypto"

### ISSUE THREAD

**Issue by VisitantP** [kokke/tiny-AES-c#146]
I have tried to encrypt an array of data using AES 256 with the following settings

C code using Visual Studio
```
#include <stdint.h>
#include <stdio.h>
#include "aes.h"

void main() 
{
	uint8_t iv[8] = { 0 };

	uint8_t key[32] = {
				104, 55, 50, 55, 3, 146, 229, 207,
				216, 152, 224, 139, 254, 236, 176, 53,
				214, 19, 90, 150, 31, 15, 178, 155,
				56, 31, 150, 74, 220, 225, 243, 6
			  };
	uint8_t in[5] = { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16 };
	struct AES_ctx ctx;
	AES_init_ctx_iv(&ctx, key, iv);
	AES_CTR_xcrypt_buffer(&ctx, in, sizeof(in));
	printf("\n\t");
	for (uint32_t i = 0; i < sizeof(in); i++)
	{
		printf("%02x%s", in[i], ((i % 16 == 15) && (i < sizeof(in)- 1)) ? "\n\t" : " ");
	}
	printf("\n");
}

```
Output is
``
        66 164 250 85 80 90 60 63 66 134 145 144 156 132 19 162
``

Python Code using PyCrypto Library:

``
k = bytearray([104, 55, 50, 55, 3, 146, 229, 207, 216, 152, 
	           224, 139, 254, 236, 176, 53, 214, 19, 90, 150, 
	           31, 15, 178, 155, 56, 31, 150, 74, 220, 225, 243, 6])
``
Output is:
`
[70, 61, 185, 228, 162, 143, 173, 252, 33, 142, 177, 224, 47, 75, 51, 28]
`

But decryption of the encrypted is proper, means it equals the initialization value.

**Comment by kokke** [comment]
Hi @VisitantP and thanks for your interest in the project

There are a few things wrong with your code, which when fixed, makes the AES-code output the same as the Python code.

first, the IV is still 128 bits - you're only allocating 64:
```C
uint8_t iv[8] = { 0 };
uint8_t iv[16] = { 0 }; // allocate 128 bits
```

For good measure, I also changed the allocation of `in`:
```C
uint8_t in[5] = { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16 };
```
... to this:
```C
uint8_t in[] = { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16 };
```

I also changed the printf-call to output decimal instead of hex (%d instead of %02x), to make comparison with the Python output easier.

I ended up compiling this code:

```C
#include <stdint.h>
#include <stdio.h>
#include "aes.h"

void main()
{
    uint8_t iv[16] = { 0 };

    uint8_t key[32] = {
                104, 55, 50, 55, 3, 146, 229, 207,
                216, 152, 224, 139, 254, 236, 176, 53,
                214, 19, 90, 150, 31, 15, 178, 155,
                56, 31, 150, 74, 220, 225, 243, 6
              };
    uint8_t in[] = { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16 };
    struct AES_ctx ctx;
    AES_init_ctx_iv(&ctx, key, iv);
    AES_CTR_xcrypt_buffer(&ctx, in, sizeof(in));
    printf("\n\t");
    for (uint32_t i = 0; i < sizeof(in); i++)
    {
        printf("%d%s", in[i], ((i % 16 == 15) && (i < sizeof(in)- 1)) ? "\n\t" : " ");
    }
    printf("\n");
}
```

... and compiling and executing it gives this output:

```bash
/tmp/tiny-AES-c-master$ gcc -Wall -Wextra test2.c aes.c -std=c99
test2.c:5:6: warning: return type of 'main' is not 'int' [-Wmain]
 void main()
      ^
/tmp/tiny-AES-c-master$ ./a.out

        70 61 185 228 162 143 173 252 33 142 177 224 47 75 51 28
        130
```

**Comment by VisitantP** [comment]
Hello,

Sorry about the syntax errors in coding. The in buffer is supposed to have only 16 elements because the same number of elements and same input is used in python code as well.

So I am correcting the code with your suggestions and running the following code:-

```
#include <stdint.h>
#include <stdio.h>
#include "aes.h"

void main()
{
    uint8_t iv[16] = { 0 };

    uint8_t key[32] = {
                104, 55, 50, 55, 3, 146, 229, 207,
                216, 152, 224, 139, 254, 236, 176, 53,
                214, 19, 90, 150, 31, 15, 178, 155,
                56, 31, 150, 74, 220, 225, 243, 6
              };
    uint8_t in[16] = { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15};
    struct AES_ctx ctx;
    AES_init_ctx_iv(&ctx, key, iv);
    AES_CTR_xcrypt_buffer(&ctx, in, sizeof(in));
    printf("\n\t");
    for (uint32_t i = 0; i < sizeof(in); i++)
    {
        printf("%d%s", in[i], ((i % 16 == 15) && (i < sizeof(in)- 1)) ? "\n\t" : " ");
    }
    printf("\n");
}
```
I am getting this as output:-

`
        44 132 234 213 90 21 10 90 56 134 190 237 0 27 84 64
`

But the Python code output is:-
`
[70, 61, 185, 228, 162, 143, 173, 252, 33, 142, 177, 224, 47, 75, 51, 28]
`

**Comment by kokke** [comment]
If I compile the code you've pasted, and run it, I get the correct output:
```
/tmp/tiny-AES-c-master$ ./a.out
        70 61 185 228 162 143 173 252 33 142 177 224 47 75 51 28
```

Please verify that you have enabled 256-bit AES mode in `aes.h`

```C
//#define AES128 1
//#define AES192 1
#define AES256 1
```

If I define AES128 instead of AES256 in `aes.h` I get the same results as you do:
```C
/tmp/tiny-AES-c-master$ ./a.out
        44 132 234 213 90 21 10 90 56 134 190 237 0 27 84 64
```
... so I'm pretty sure that is the problem :)

**Comment by kokke** [comment]
Closing the issue, since it seems to be usage-related.

@VisitantP feel free to keep posting if my proposed fix isn't working for you, or if you have other questions

**Comment by VisitantP** [comment]
Thanks for the help, that was pure brilliance.  Why don't we make the mode specification i.e AES256, AES128 or AES192 as a part of the structure AES_ctx? wouldn't that be more appropriate?
Also why don't we have more flexibility for defining the counter as in python. For instance in python, the counter is composed of a fixed Prefix and Suffix along with a Counter register, while the total length of the Prefix, Suffix and Counter register offers more flexibility in the design.

**Comment by nathe97** [comment]
I have the same problem here, tested with python i have same output as you
