### ISSUE TITLE
Limited flexibility in configuring AES mode

### ISSUE THREAD

**Issue by VisitantP** [kokke/tiny-AES-c#147]
Why don't we make the mode specification i.e AES256, AES128 or AES192 as a part of the structure AES_ctx? wouldn't that be more appropriate? 
Also why don't we have more flexibility for defining the counter as in python. For instance in python, the counter is composed of a fixed Prefix and Suffix along with a Counter register, while the total length of the Prefix, Suffix and Counter register equals the block length, my opinion is that this would offer more flexibility in the design.

I am sharing the documentation link of counter structure implemented in python [here](https://pycryptodome.readthedocs.io/en/latest/src/util/util.html#Crypto.Util.Counter.new).

**Comment by kokke** [comment]
Hi @VisitantP and thanks for your comments.

One of the main design goals of this project is small resource footprint, especially small binary size.. Supporting a more flexible API with e.g. support for dynamic key-size would increase the binary size significantly - at least I cannot imagine a way to implement what you suggest without doing so.

I don't see much benefit of the proposed counter API, besides a small bit of convenience. The library is simple enough that most people can add whatever wrapper they wish for, obtaining the flexibility they want.

To say it roughly: mostly anything that adds to the binary size without also adding functionality or fixing bugs, will not be included here.

I hope this answers your question. 

Feel free to continue this thread, if you have further comments or questions :)
