### ISSUE TITLE
Support AES256/CBC/PKCS7Padding ?

### ISSUE THREAD

**Issue by VincentChen1212** [kokke/tiny-AES-c#148]
HI

This is a good Project.

and
Is this Project Support AES256/CBC/PKCS7Padding ???
or something can reference ??

Thanks

**Comment by kokke** [comment]
Hi @VincentChen1212 and thanks for the compliment :)

The project supports AES128/192/256 and ECB, CBC and CTR mode. 

Padding is not provided, but it is fairly easy to implement PKCS7 yourself. See for instance: https://en.m.wikipedia.org/wiki/Padding_(cryptography)#PKCS7

**Comment by VincentChen1212** [comment]
Hi,
Thanks your helping.
Because I can't use C/C++, I need someone to help me.

Thanks
