### ISSUE TITLE
CTR example does not Encrypt/Decrypt

### ISSUE THREAD

**Issue by fweinrebe** [kokke/tiny-AES-c#153]
The example in Test.c for CTR mode is not complete. It merely calls the same method but the parameter is only displayed and never used to decide if it is encrypted or decrypted.

**Comment by kokke** [comment]
Hi @fweinrebe - in CTR mode encryption and decryption is the same operation.

`test.c` is not meant to be a comprehensive test-suite; it is meant to quickly demonstrate usage.

Quoting from "https://github.com/kokke/tiny-AES-c/issues/142"

> I have done a lot more testing than what is in test.c and indeed encryption and decryption works as advertised even though the test-file doesn't test very thoroughly.
> 
> The test-code is meant to be a quick way for users to verify against the NIST vectors described in SP 800-38. It is not meant to convince you of correctness or robustness.
