### ISSUE TITLE
tiny-AES-c and AES-IN

### ISSUE THREAD

**Issue by VaasKahnGrim** [kokke/tiny-AES-c#160]
While digging around looking further into AES I came across something from Intel called AES-NI which is apparently hardware accelerated AES.

I'm quite interested in knowing if tiny-AES-c supports it and if not could a feature request be opened for adding support in for it?

**Comment by kokke** [comment]
Hi @VaasKahnGrim

I don't think the project will ever support hardware-acceleration as it is orthogonal to portability in my opinion.

Using no hardware-acceleration means the code works the same on all platforms, and can be tested on all platforms. Intel AES-NI instructions are not supported on microcontrollers, for which this library is mainly intended.

If you are interested in a hardware-accelerated AES library, I recommend you look into projects like OpenSSL etc.

**Comment by VaasKahnGrim** [comment]
Would OpenSSL be useful for handling file encryption? alternativly do you know of any useful resources for using AES-NI? I originally opened this issue as I couldn't seem to find any info on implementing AES-NI or if it was already implemented

**Comment by kokke** [comment]
Hi @VaasKahnGrim - any AES implementation can be used for files, networking, you name it - there is nothing special about files :)

I don't know of any resources for AES-NI, but I can find several projects here on github that seemingly has something to do with AES-NI. You could start there, or with just google.

This seems a good intro e.g. : https://gist.github.com/acapola/d5b940da024080dfaf5f
