### ISSUE TITLE
Removing salt and padding

### ISSUE THREAD

**Issue by Gungeoneer** [kokke/tiny-AES-c#164]
I'm trying to understand the code that you have written and I had one question : 

Does this implementation make use of salt for AES-128 ECB and if yes, how do I perform AES-128 ECB encryption in nosalt mode?

**Comment by kokke** [comment]
Hi @Gungeoneer and thanks for your interest.

>Does this implementation make use of salt for AES-128 ECB and if yes, how do I perform AES-128 ECB encryption in nosalt mode?

No salting is performed for ECB-mode. I've never heard the salting-term used for block-ciphers. Usually it's called an IV (initialization vector)? Maybe I'm misunderstanding you.

If you want to control some initial entropy, I recommend you use CBC mode instead.

In general I would recommend against ECB-mode unless you _really_ know what you are doing.

See [wikipedia's article on block-ciphers](https://en.wikipedia.org/wiki/Block_cipher_mode_of_operation#Electronic_codebook_(ECB)) for a better explanation of the problem (check the image of Tux).

**Comment by kokke** [comment]
Also, there is no padding - you have to handle that yourself.

From the README: 
>No padding is provided so for CBC and ECB all buffers should be multiples of 16 bytes. For padding PKCS7 is recommendable.

See [the PKCS page on wikipedia](https://en.wikipedia.org/wiki/PKCS) for more information about some standards for padding.

I hope that answers your questions. If not, please feel free to reopen the issue or just post your follow-up questions :)
