### ISSUE TITLE
Performance seems much slower than openssl

### ISSUE THREAD

**Issue by surpass007** [kokke/tiny-AES-c#174]

**Comment by Nable80** [comment]
Hi!
It's not possible to achieve both high speed and small code (both source code and binary size) size at the same time, there'll always be a trade-off between them. This library is mostly aimed at embedded devices where code size and readability matters much more than speed (thus its name). At the same time openssl supports much more modes and architectures, it has a lot of optimizations (including inline assembly) that make source code much more complex and its binary size isn't suitable for MCUs at all.

These libraries have different target use-cases and can't replace each other, it's up to you to decide what is more important in each particular case and choose the right tool.

**Comment by kokke** [comment]
Thank you for answering this question for me @Nable80 :)

Closing

**Comment by Nable80** [comment]
I'm happy to see you're active again! What do you think about adding some notes in README about speed-vs-size trade-off and project (non-)goals?

**Comment by kokke** [comment]
Thank you @Nable80 ;D :+1: 

I think it's a great idea. I will look into formulating something..

 I also think I should also make some kind of FAQ with common usage-errors. We do get a lot of the same questions/problems over and over.. (NOTE this question is not such a "repeater"-question!)

**Comment by kokke** [comment]
What do you think about https://github.com/kokke/tiny-AES-c/commit/7279b02ac9decf032d9e519b2d400ee7d76f5e89 ?

**Comment by Nable80** [comment]
OK, here's how I see this part:
1. ``Note:`` → ``Important notes:``, it should also be bold, probably it's better to achieve this by marking it as a section or sub-section (``###`` or ``##``). Some common pitfalls are already described there but this section is highlighted now.
2. Probably it makes sense to state explicitly that it's not possible to achieve both goals at the same time. Something like this: _This library is intended for cases where portability, code size (readability?) and low memory footprint are more important than speed. If speed is a concern, you can try more complex libraries, e.g. Mbed TLS, OpenSSL, etc._

**Comment by kokke** [comment]
Good input @Nable80 thank you - I think your description of the trade-offs is really good.
