### ISSUE TITLE
Incorrect usage? 

### ISSUE THREAD

**Issue by cyrusbehr** [kokke/tiny-AES-c#184]
Since there is no complete sample code, I had to guess at how to use the library, and it doesn't look like I'm using it correctly. Refer to the sample code below:

```
#include <iostream>
#include <vector>
#include <cstring>
#include "aes.hpp"
#include <string>

int main() {
    const std::string myString = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa";
    std::cout << "Length: " << myString.size() << std::endl;

    const uint8_t key[16] = {'9','f','3','c','8','3','4','8','a','f','d','5','c','1','7','c'};

    AES_ctx ctx{};
    AES_init_ctx(&ctx, key);

    std::vector<uint8_t> enc;
    enc.resize(myString.size());
    memcpy(enc.data(), myString.data(), myString.size());
    std::cout << "Decrypted: " << std::string((char *)enc.data(), enc.size()) << std::endl;

    AES_CBC_encrypt_buffer(&ctx, enc.data(), myString.size());

    std::cout << "Encrypted: " << std::string((char *)enc.data(), enc.size()) << std::endl;

    AES_CBC_decrypt_buffer(&ctx, enc.data(), enc.size());

    std::cout << "Decrypted: " << std::string((char *)enc.data(), enc.size()) << std::endl;

    return 0;
}

```

Running this program produces the following output: 
```
Length: 32
Decrypted: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
Encrypted: Q�.pLx�쳢`�](��������ޝ����.�
Decrypted: �o�����ܿ���O�aaaaaaaaaaaaaaaa
```

Am I using the library incorrectly? Why are the two decrypted strings different?

**Comment by cyrusbehr** [comment]
Would be great if you could include some sample code on how to use the library for crypto beginners like me.

**Comment by kokke** [comment]
@cyrusbehr the basics of symmetric crypto such as AES is pretty straight forward.

CBC and ECB mode are block ciphers - they work in blocks of 16 byte. So you need to handle padding. There are different padding schemes and all the abbreviations sound fancy, but basically they amount to padding with 1,2,3,4,5 or n, n+1,n+2,n+3 for n missing bytes to be padded. It's super simple.

If you want to avoid padding all together, use CTR mode which is a streaming cipher. That mode will encrypt/decrypt in arbitrary sizes.

You can always work on messages of size X by doing 10 operations on X/10 bytes at a time. You just need to control the IV between each invocation of encrypt() / decrypt().

This wiki illustrates how it works very well graphically: https://en.wikipedia.org/wiki/Block_cipher_mode_of_operation

**Comment by cyrusbehr** [comment]
I did not see `test.c`, but I will have a look thanks. 

Thanks for taking the time to explain, appreciate it.

**Comment by kokke** [comment]
No problem :) Feel free to re-open or keep posting if you still have problems with the library.
