### ISSUE TITLE
rijndael-256 support

### ISSUE THREAD

**Issue by bsergean** [kokke/tiny-AES-c#190]
Hi there,

I know this will likely be out of scope, but how hard do you think it would be to support rijndael-256, which is the grand-father of AES, with just one difference in the block size I believe, which can be 256-bits while AES limit it to 128 iirc.

If you feel this isn't right, could you advice on how to write a tiny-rijndael-256, I hope the changes are small. Thanks !

https://web.archive.org/web/20130305143117/http://csrc.nist.gov/archive/aes/rijndael/Rijndael-ammended.pdf#page=1

**Comment by kokke** [comment]
Hi @bsergean and thanks for your interest in the project! :)

See this issue for a discussion of the same question https://github.com/kokke/tiny-AES-c/issues/171

Very quickly: Rijndael has variable key, block + round-number. AES has "hard-coded" round-number + block-size and this code has been "optimized" slighty for this case, i.e. loops have been unrolled etc.

You would be better off with an earlier version of this project, before optimizations. Then you'd probably be able to "configure" it to pure Rijdael or rewrite it. I don't have the energy myself unfortunately.

Best of luck :) :+1:
