### ISSUE TITLE
AES CBC not working

### ISSUE THREAD

**Issue by zgdump** [kokke/tiny-AES-c#192]
Hello. Trying to use your library and came across a problem. AES CBC is not working correctly.

NB. ECB working well.

## Issue description

I tried to encrypt the string with AES CBC on the microcontroller and then decrypt it on the computer. But every time there was broken data, the data was not decrypted correctly. There is a suspicion of incorrect behavior of the encryption function.

Test on atmega328p and stm32f411 

## How to repro

To reproduce problem try:

1. Create byte array of the key and the buffer
2. Copy any data to the buffer
3. Encrypt, decrypt the buffer
4. Compare original data and decrypted

## Example repro

Example reproducible sketch for Arduino:

<details>
<summary>Code</summary>

```C++
#include "aes.hpp"
struct AES_ctx ctx;

uint8_t key[] = {
  0x60, 0x3d, 0xeb, 0x10, 0x15, 0xca, 0x71, 0xbe, 0x2b, 0x73, 0xae, 0xf0, 0x85, 0x7d, 0x77, 0x81,
  0x1f, 0x35, 0x2c, 0x07, 0x3b, 0x61, 0x08, 0xd7, 0x2d, 0x98, 0x10, 0xa3, 0x09, 0x14, 0xdf, 0xf4
};

uint8_t buf[16] = { 0 };

void printHex(uint8_t num) {
  char hexCar[4];

  sprintf(hexCar, "%02X ", num);
  Serial.print(hexCar);
}

void printByteArrayAsHexStringToSerial(uint8_t buf[]) {
  for (uint16_t i = 0; i < 16; i++) {
    printHex(buf[i]);
  }
  Serial.println();
  Serial.println();
}

void setup() {
  Serial.begin(9600);
  delay(10);

  AES_init_ctx(&ctx, key);

  Serial.println("Buffer at start: ");
  printByteArrayAsHexStringToSerial(buf);

  memcpy(&buf, "HELLO", 5);

  Serial.println("Buffer after copy data: ");
  printByteArrayAsHexStringToSerial(buf);

  //while (true) {

  AES_CBC_encrypt_buffer(&ctx, buf, 16);

  Serial.println("Buffer after encryption: ");
  printByteArrayAsHexStringToSerial(buf);

  AES_CBC_decrypt_buffer(&ctx, buf, 16);

  Serial.println("Buffer after decryption: ");
  printByteArrayAsHexStringToSerial(buf);
  Serial.write(buf, 16);

  Serial.println();
  Serial.println();
  delay(5000);
  //}
}

void loop() {}
```

</details>

Output:

```
Buffer at start: 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 

Buffer after copy data: 
48 45 4C 4C 4F 00 00 00 00 00 00 00 00 00 00 00 

Buffer after encryption: 
E2 71 EA C3 0F EF 43 29 00 43 4A EA BA D9 05 54 

Buffer after decryption: 
AA 34 A6 8F 40 EF 43 29 00 43 4A EA BA D9 05 54 
```

Expected output:

```
Buffer at start: 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 

Buffer after copy data: 
48 45 4C 4C 4F 00 00 00 00 00 00 00 00 00 00 00 

Buffer after encryption: 
E2 71 EA C3 0F EF 43 29 00 43 4A EA BA D9 05 54 

Buffer after decryption: 
48 45 4C 4C 4F 00 00 00 00 00 00 00 00 00 00 00 
```

**Comment by Nable80** [comment]
Hi! I think you forgot about IV (initialization vector), this is important for CBC mode.
See this example in tests, please: https://github.com/kokke/tiny-AES-c/blob/3f69a5899e58e2e398e8c32ce7b3a954dd593ed4/test.c#L214

https://en.wikipedia.org/wiki/Block_cipher_mode_of_operation#CBC

**Comment by Nable80** [comment]
@zgdump is your issue solved now?

**Comment by zgdump** [comment]
> Hi! I think you forgot about IV (initialization vector), this is important for CBC mode.
> See this example in tests, please:
> 
> https://github.com/kokke/tiny-AES-c/blob/3f69a5899e58e2e398e8c32ce7b3a954dd593ed4/test.c#L212-L217
> 
> https://en.wikipedia.org/wiki/Block_cipher_mode_of_operation#CBC

Hello, thank you for your advice!

I figured out why the encryption didn't work. 

First, encryption and decryption require *different contexts* to be initialized in the same way.

Second, need to take *the pointer to the key* and *the pointer to the iv* in the `AES_init_ctx_iv`. I just used a variable and the microcontroller perceived an array of bytes as an address in memory.

Thanks, close issue.
