### ISSUE TITLE
Unstable data response using CTR mode with different data

### ISSUE THREAD

**Issue by hugorojasppm** [kokke/tiny-AES-c#193]
I'm using the CTR mode to make a crypt/decrypt methods that allows me to cipher data from one endpoint to another.

This is the approach I made and is working as expected.

```
   #include <stdio.h>
   #include <stdlib.h>
   #include <string.h>
   #include <stdint.h>
   #include "aes.h"

char* cryptData(char* data) {    
    uint8_t key[] = "Gg3KXqrtzMfhqhm8";
    uint8_t iv[]  = "UVcuZbxQ8y73QGr7";
    uint8_t str[strlen(data)];
    strcpy(str,data);
    size_t data_size = strlen(data);

    struct AES_ctx ctx;
    AES_init_ctx_iv(&ctx, key, iv);
    AES_CTR_xcrypt_buffer(&ctx, str, data_size);

    const char * plainText =  (char *) str;
    size_t input_size = strlen(plainText);
    char * encoded_data = base64_encode(plainText, input_size, &input_size); //VERIFIED THIS WORKS
    printf("Encoded Data is: %s \n",encoded_data);

     return (char *)encoded_data;
}
```

```
char* decryptData(char* encoded_data, int data_size) {
    uint8_t key[] = "Gg3KXqrtzMfhqhm8";
    uint8_t iv[]  = "UVcuZbxQ8y73QGr7";
    struct AES_ctx ctx;

     size_t decode_size = strlen(encoded_data);
    char * decoded_data = base64_decode(encoded_data, decode_size, &decode_size);  //VERIFIED THIS WORKS

    uint8_t newStr[strlen(decoded_data)];
    strcpy(newStr,decoded_data);

    AES_init_ctx_iv(&ctx, key, iv);
    AES_CTR_xcrypt_buffer(&ctx, newStr, data_size);

    char * result =  (char *) newStr;
    printf("\nResultado del decode: %s\n", (char *) result);
    return result;
}
```

```
int main(void){
    char* dataToEncrypt = "[6794 x41206','website':'conrad.com'},{'name':'Clementina DuBuque','email':'Rey.Padberg@karina.biz','phone':'024-648-3804','website':'']";
    char* dataWithError = "[6794 x41206','website':'conrad.com'},{'nam332-32342424e':'Clemeentina DuBuque','email':'Rey.Padberg@karina.biz','phone':'024-648-3804','website':'']";
    int data_size = strlen(dataToEncrypt);
    char* resultCrypt = cryptData(dataToEncrypt);
    char* resultDecrypt = decryptData(resultCrypt , data_size);
    return 0;
}
```

Using **dataToEncrypt** works as expected. But if i change to **dataWithError** gives me an error and the result could not be decrypted as expected it throws an error like this:

Response: **6794 x41206','website':'conrad.com'},{'nam332-32342424e':'Clemeentina DuBuque','emailH��g�@"�$���͗a��m�Y��i�H��$�=�w�dR�~(���lt
��]�T^���r   U?���$=�m�9'
����"�=�#dO���0r:�w��&A������ޮ��/3*x���a,Aϙ�?ʃF^ސ�$��8�p��RN��Z�G�#�xћ����b�ٿmi�|+dpҥ�
                 ��fm��UVcuZbxQ8y73QGrAUVcuZbxQ8y73QGr7**

It seems that starts decoding well, and then it breaks with unexpected result.
I'm using  => #define AES128 1 in the aes.h

Is there anything wrong?. Why does it work with one string and breaks with the other one?
How long can be the input to use the AES_CTR_xcrypt_buffer method?

Thank you in advanced.

**Comment by Nikolay-Po** [comment]
Depends on your target architecture and the compiler. Most probably the problem is in this line

`uint8_t str[strlen(data)];`

And your compiler is unable dynamically change the size of arrays. It uses smaller size of firstly called shorter dataset. Then the execution is crashing at longer string.
Try to fix the size of every array you are using at the value which fits largest data set including terminator.

**Comment by hugorojasppm** [comment]
The problem was that in certain data the encrypt returns NUL BYTE and the strlen of that string got truncated by the last character before the NUL BYTE. So, the solution was to change the strcpy(str,data); to memcpy which does not care about the NUL BYTE.
