### ISSUE TITLE
There is no clear license

### ISSUE THREAD

**Issue by HSCOO** [kokke/tiny-AES-c#195]
There is no clear license, which prevents me from using it. My industry must use a clear license, which can avoid risks as much as possible.

**Comment by jmons** [comment]
Apologies, there is a clear license, its just got a bit of a frustrating name for 'official' work:

https://github.com/kokke/tiny-AES-c/blob/master/unlicense.txt

It's been linked correctly on the project and has this in the root.

**Comment by kokke** [comment]
Hi @HSCOO and thanks for your interest in this project :)

Can you please elaborate on what you find unclear about the current license? The name, the terms or ... ?

Unlicense has both OSI and FSF approval as per https://opensource.org/licenses/unlicense and https://www.gnu.org/licenses/license-list.html#Unlicense 

I will probably never change the license as IIUC that requires an explicit agreement from all contributors, which I feel is infeasible.

I am closing the issue, but feel free to get back if you have further to add to the discussion :)
