### ISSUE TITLE
tiny-AES-c with vcpkg: using AES256

### ISSUE THREAD

**Issue by Maverick10** [kokke/tiny-AES-c#199]
I used to include the repo directly in my project. Recently, I decided to use it through vcpkg and I ran into the following problem:
I needed to use AES256 and there's no way to do that (not that I know of) except to modify the code in `aes.h` file to define the macro as per the documentation.
Of course one of the perks of using vcpkg is that you don't have to deal with the code of the library you're using. So is there any way to achieve what I want without modifying the code?

**Comment by kokke** [comment]
Hi @Maverick10 

I am completely unfamiliar with vcpkg, so I am afraid I cannot help you :(

Currently, the key-size is hard-coded, so I don't think so.
