### ISSUE TITLE
Multiblock CBC decryption failed

### ISSUE THREAD

**Issue by b-s-a** [kokke/tiny-AES-c#20]
Current CBC decryption implementation causes damage of Iv data when you reload your input buffer. So any next call of AES128_CBC_decrypt_buffer(out, in, size, NULL, NULL) causes invalid result. To solve it add new buffer for Iv data which filled in decrypt function before exit.

**Comment by rassul** [comment]
Can you explain what you mean by adding new buffer for Iv data. How is it done?

**Comment by b-s-a** [comment]
See, Iv is just pointer to uint8_t. It initialized on line 566 by input. So when I reload this input buffer and then try to continue decoding (I use this code in small RAM application) I receive invalid result.
To fix it without lose compatibility:
static uint8_t* Iv; -> static uint8_t Iv[KEYLEN];

and all Iv = xx replace by BlockCopy(Iv, xxx)

**Comment by rassul** [comment]
Thank you very much for the prompt response and the explanation. Also, thanks for putting the source code for public.


Russell





________________________________

**Comment by sdrsdr** [comment]
Both encrypt and decrypt  work in non streaming manner. For streaming implementation you need to copy the final iv bytes back to the calling function, thus you can properly "resume" en/decryption in streaming mode

**Comment by kokke** [comment]
Closing because issue is fixed after merging #76
