### ISSUE TITLE
Zenner default AES keys would be needed

### ISSUE THREAD

**Issue by 4K901** [kokke/tiny-AES-c#210]
Hello,

I'm testing a simple USB receiver where I can catch the telegrams of two Zenner watermeters from my household (type - Minomess wM-Bus C1 Mode and type EDC wireless M-bus module T1 Mode)

I tried to look trough the project, but can not figure out how can I find out the default AES keys for the decryption.

Herebelow the raw, encrypted telegrams from the two meters:
ID 14340330:
3644496A4187025001377230033414496A010776002025F42F261F8EFA0D14A0B28DBFF3468906D97405FB723A26F884B344CA5199B12F

ID 15496853:
6644496A1483025514377253684915496A0007C30050054512796939A3AFECD7417FC33AC83CFE38520B8B92508FBC6210248E342F6950A61933F3D4258FBDD459FFE02B5DEB5169BD5AADB62905967D24317553991DFC29E22FE46AE3013C9F92F28832CFEAE0

Sorry I'm not an expert of Github and not sure if I can ask this kind of question here. If this wasn't the right place, please just drop me a line where can I ask something like this.

Thank you in advane.

**Comment by kokke** [comment]
Hi @4K901 :)

Maybe I’m misunderstanding your question, but AES has no “default key”. 

The security comes from the key being secret and large enough (16 bytes / 128bits) to make it impossible to try all possible options. 

You cannot (generally speaking) infer the key from encrypted data (that would defeat the purpose of encryption). You must know the key to be able to decrypt the data.

A quick look on Google indicates a possibility of obtaining the AES keys from Zenner: https://www.mz-connect.com/shop/info-about-iot-device-keys

Unfortunately I cannot help you further. You need to get in contact with someone who knows the key your Zenner devices are using.

Best of luck 😃

**Comment by kokke** [comment]
Direct link to guide: https://www.mz-connect.com/shop/media/pdf/45/e7/7b/190527_UserGuide_ZENNER-direct-delivery-note-portal.pdf

**Comment by 4K901** [comment]
Thanks for the quick response.
