### ISSUE TITLE
USML or ECCN number?

### ISSUE THREAD

**Issue by paul144hart** [kokke/tiny-AES-c#214]
Is there a USML or ECCN number for this software?
Thanks,

**Comment by kokke** [comment]
Hey, thanks for your interest in this project :slightly_smiling_face: 

> Is there a USML or ECCN number for this software?

Not that I know of. May I ask why you're asking for this, just out of curiosity? :slightly_smiling_face:

**Comment by kokke** [comment]
IANAL, but it looks like publicly available software is exempt from export restrictions if used for non-military purposes:

From https://www.bis.doc.gov/index.php/policy-guidance/encryption/1-encryption-items-not-subject-to-the-ear

> There are no EAR obligations associated with the item unless it is exported, reexported, or transferred. These are specially defined terms in the EAR. See Section 734 for guidance on the definition of export, reexport, and transfer.
> 
> Certain foreign made items that contain less than a de minimis amount of U.S. origin content are not subject to the EAR. See 734.4 of the EAR.
> 
> Publicly Available:
> 
> **Encryption items that are publicly available as further described below are not subject to the Export Administration Regulation**. Sections 734.3(b)(3) and 734.7 define what is publicly available and published. Common examples are free apps posted online or mass market software available as a free download.

and

> Note 2: While open source code itself may be publicly available and not subject to the EAR, an item is not considered publicly available merely because it incorporates or calls to publicly available open source code. Rather, a new item with encryption functionality has been created which would need to be evaluated as a whole under the EAR.

From https://www.bis.doc.gov/index.php/licensing/commerce-control-list-classification/export-control-classification-number-eccn it looks like the ECCN number/code should be 5D002 -> https://www.bis.doc.gov/index.php/documents/regulations-docs/2337-ccl5-pt2-4/file
