### ISSUE TITLE
CBC Mode Final Padded Block Bug

### ISSUE THREAD

**Issue by Mick-P** [kokke/tiny-AES-c#30]
Just noted that the CBC encrypt code does NOT apply the IV to the final block when the length of the plain text is not an exact multilple of KEYLEN. In this instance the if(remainders>0){ } code after the FOR loop is executed and in that section the IV is NOT applied.

**Comment by kokke** [comment]
Could you verify if this branch fixes your issue ?

https://github.com/andreas-wehrmann/tiny-AES128-C/commit/f8b5ea32ba7fae68b4179e5d22cef33f454e2045

I don't have the time to test it myself, but it sounds like this might fix your problem ?

**Comment by Mick-P** [comment]
Hi
Yes! BTW the same bug exists in the decrypt code and I think is uncorrected in Andreas solution. It does not cause a problem because normally the decrypt function is only required to work with data that has already been encrypted and hence is an exact number of complete blocks long and so there is no need to handle the 'remainders'


reagrds
Neuroscot Ltd. 11 Bankhead Broadway Edinburgh EH11 4DB Tel. 0870 753 6364 / 0131610 0225 Fax 0870 753 6365 / 0845 868 1733 SKYPE: neuroscot_office www.neuroscot.co.uk Registered In Scotland: SC151587 VAT: GB444155756 



Original message

**Comment by kokke** [comment]
Fixed in https://github.com/kokke/tiny-AES-c/commit/84468b291bb7c258b40870dd999f75cbff00aa50#diff-9789999dc6dd261657c63f757d1e680d
