### ISSUE TITLE
How to handle short string / files

### ISSUE THREAD

**Issue by lsatenstein** [kokke/tiny-AES-c#37]
When encrypting the string, if the string is less than a multiple of 16, pad the string with hex zeros to make the length become an exact multiple of 16.  In the final byte of the padded value, indicate as a character (1-x0f), the actual length of the data that is valid within the padded block.

If the string is exactly a multiple of 16 bytes, add a padded block of hex zeros.  The final byte will contain hex zero, which states that none of the final block is used.

When decoding,  examine the last block of 16 bytes. That final byte indicates how many characters of this last block are valid.

I use this technique elsewhere, When I get a chance I will post my solution. My solution works with ecb or with cypher block chaining mode.

**Comment by kokke** [comment]
Cool! Thank you for the explanation of the technique :)

The library is intended to be a bare-bone library with a small memory footprint, that people can build upon.
You are welcome to contribute example code that shows off the technique, handling strings and/or files.

I strive to review all pull requests and respond to them when I fully understand the consequence of accepting it. Unfortunately my spare time is sparse, so I am often slow to respond to changes in the main-algorithm, but somewhat quicker when it comes to additions; i.e. patches that do not alter the main library.
