### ISSUE TITLE
Redundant BlockCopy() call at start of AES128_CBC_encrypt_buffer()

### ISSUE THREAD

**Issue by camieac** [kokke/tiny-AES-c#45]
Summary
------------

At the beginning of the CBC encrypt/decrypt functions the contents of the input buffer is copied to the output buffer, this is also done for ECB mode. The initial copy in ECB mode is necessary, but seems to be redundant in the CBC functions. The exact same copy is later made in the for loop iterating through the AES blocks.

A visual inspection of `AES128_CBC_encrypt_buffer()` and `AES128_CBC_decrypt_buffer()` should confirm the issue.

Testing
---------

The tests pass with the redundant copy removed.

Fix
----

Remove redundant call to `BlockCopy()` in `AES128_CBC_encrypt_buffer()` and `AES128_CBC_decrypt_buffer()`.

Existing Fixes
-----------------

I had a hunt through the pull requests and found the following un-merged requests that address this issue:
- https://github.com/kokke/tiny-AES128-C/pull/18 Removes redundant copy, as well as other changes.

- https://github.com/kokke/tiny-AES128-C/pull/23 Lots of fixes to CBC implementation including this redundant block copy.

Conclusion
--------------

This is a simple fix that can shave off a few redundant CPU cycles, unless the compiler is already optimising it out for you :smile:

I am happy to prepare a pull request addressing this issue only, if there's interest.

**Comment by kokke** [comment]
Bump. What's the status on this one now? I think some redundancy and other idiocy on my part was removed, thanks to PR #58

**Comment by kokke** [comment]
As far as I can tell, this issue was fixed with PR #58
