### ISSUE TITLE
Cannot handle buffered input

### ISSUE THREAD

**Issue by bill1davis** [kokke/tiny-AES-c#49]
I am using your code for an embedded application (thank you very much BTW) that decrypts packetized ciphertext on the fly.  The cipher text arrives on my embedded box in a circular buffer.  Your implementation relies on the previous input persisting across calls to be reused as the next IV.  A simple fix is to declare Iv as a byte array and then replace the pointer assignment with a memcpy.

	for (i = 0; i < length; i += KEYLEN)
	{
		BlockCopy(output, input);
		state = (state_t*)output;
		InvCipher();
		XorWithIv(output);
    #ifdef STATIC_INPUT_ONLY
		Iv = input;
    #else 
            memcpy(Iv,input,sizeof(Iv));
    #endif
		input += KEYLEN;
		output += KEYLEN;
	}

**Comment by kokke** [comment]
Thank you very much for your contribution, also I'm always happy to hear about applications of the project :)

**Comment by g1deonr** [comment]
I also fell over this issue. If you try to decrypt in blocks the first block is correct but 2nd, 3rd... blocks corrupt the first 16 bytes of that block.

**Comment by kokke** [comment]
Closing because issue is fixed after merging #76
