### ISSUE TITLE
Add examples.

### ISSUE THREAD

**Issue by AraHaan** [kokke/tiny-AES-c#65]
I would like some example programs that can use this to encrypt or decrypt or both files on the filesystem as well (like opening a file, reading the data, encrypting/decrypting it, writing the data, closing the file). This is because I might be thinking of Making an exe compressor or something with this and (maybe zlib) if I can figure out memory zlib compressing as well.

**Comment by kokke** [comment]
Hi @AraHaan and thank you for considering using this project :)

Check out this Pull-Request for inspiration on how to implement file en-/decryption: https://github.com/kokke/tiny-AES-c/pull/10

**Comment by androidovshchik** [comment]
Hi
I wrote android app which is using this library via ndk
https://github.com/androidovshchik/TinyAES
Have a look! Enjoy
