### ISSUE TITLE
No Input Output Parameters

### ISSUE THREAD

**Issue by ErDeepChand** [kokke/tiny-AES-c#66]
I want to use these files in the Android NDK but unable to convert the string passed from java end to convert in the uInt_8 array and return an output string as being dumb in C.
Please, can you make the methods so that the return the encrypted string as output string and accept an input as plain text so that I can implement it easily?
Also, I want to provide the iv and key in the string format.

So please take plainText = "plaintext", iv="iv_key213123", key="key_qwerwqer", and return the output as 
cypherText.
Hope it makes sense?

**Comment by kokke** [comment]
Hi @ErDeepChand and thanks for reading my code :)

What you are asking is outside of the project scope and, with no intent to offend, is not difficult to implement in C.

I suggest you undertake the implementation of the API you are requesting yourself.

The `uint8_t`-type is just an unsigned 8-bit wide `char` with an integer value between 0 and 255.

I will not add code like you are asking, to the project, but if you show me what you have tried so far, I will gladly help you debug the code.

Your request seems better suited for a Q&A site like stackoverflow.com in my opinion.

**Comment by androidovshchik** [comment]
Hi
I wrote android app which is using this library via ndk
https://github.com/androidovshchik/TinyAES
Have a look! Enjoy
