### ISSUE TITLE
iv variable

### ISSUE THREAD

**Issue by EdTodd** [kokke/tiny-AES-c#67]
Am I supposed to add logic to generate iv values or is this built in somewhere?

**Comment by kokke** [comment]
Hi @EdTodd and thanks for your question :)

The short answer is: You are supposed to generate the IV yourself.

Originally I implemented the CBC-mode as a demonstration of how to use ECB as a "building-block". That was the original intent at least.

How you use the IV depends greatly on the mode of operation you are planning on using:
https://en.wikipedia.org/wiki/Block_cipher_mode_of_operation

I hope this answers your question sufficiently ?
