### ISSUE TITLE
Not working on Arduino Uno, AVR not even booting

### ISSUE THREAD

**Issue by aimass** [kokke/tiny-AES-c#68]
Hi, thanks for the great code. It looks really clean and elegant implementation, and I love the fact you have CBC, but sadly I can't get it to work.

I placed the files as-is in the libraries directory and just by including "aes.h" the program compiles but: 

1) The ram usage spikes by 764 bytes. If you get 200 bytes on a 32 bit processor how can I get 3x that in an 8 bit one?
2) If I upload the code just with the include, the Arduino will fail to start, like it just hangs.
3) If I just comment the include line, the program uploads and the AVR starts working again.

I noticed you said you have tested this in AVR. Can you pls. post instructions on how you got it working? Perhaps I am doing something wrong.

TIA,
Alex

**Comment by kokke** [comment]
Are you including the test-files? Because the whole thing should not take up that much RAM.

Try having a look in the memory map / listing, to see what is taking up the RAM.

**Comment by aimass** [comment]
Yeah it was the test code, how dumb! 

But it was even weirder than that. I am not sure but I think the Arduino IDE was using the Makefile because when I deleted the test.c file the sketch refused to compile. Maybe it was even overriding main() who knows...

Anyway I got the whole thing working and these are the steps and some observations that other Arduino users can follow:

1) Clone the project in a working directory
2) Create a new directory in your ~/Arduino/libraries (e.g. tiny-aes) and in it softlink aes.c from your working directory to aes.cpp in your library directory. Do the same with aes.h but do not change the name.
3) At this point you should be able to compile, run and test the library in your arduino sketch just by including normally as  #include "aes.h". Without any mods the library will take up 546 bytes of RAM and it's pretty fast. If you want to reduce this RAM follow the next steps, but note that the code will get slower.
4) (on or around line 41) Edit aes.c and #include <avr/pgmspace.h>
5) (on or around line 95) Change static const uint8_t sbox[256] to const PROGMEM uint8_t sbox[256]
6) (on or around line 114) Change static const uint8_t rsbox[256] to const PROGMEM uint8_t rsbox[256]
7) (on or around line 134) Change static const uint8_t Rcon[11] to const PROGMEM uint8_t Rcon[11]
8) (on or around line 173) Change return sbox[num]; to return pgm_read_byte_near(sbox + num);
9) (on or around line 178) Change return rsbox[num]; to return pgm_read_byte_near(rsbox + num);
10) (on or around line 232) Change tempa[0] =  tempa[0] ^ Rcon[i/Nk]; to tempa[0] =  tempa[0] ^ pgm_read_byte_near(Rcon + i/Nk);
11) Compile and the lib should just use 278 bytes of RAM

There are probably more optmizations that could be done but 278 bytes is amazing for our application so we are happy with these simple and safe changes. Reading from PROGMEM  does not seem to affect performance too much.

Here is our fork with the changes for reference and the specific commit:

https://github.com/AgroMe/tiny-AES-c/commit/a640b8cbbc45c5eb3d7208af5d14f5d36423132d
https://github.com/AgroMe/tiny-AES-c

Really great lib! 
Thanks @kokke et al. great job!!

**Comment by kokke** [comment]
Hi Alejandro, thanks for the detailed description :)

I could imagine the Arduino IDE getting confused about the Makefile and the extra `main()`-function.
I have only used the Arduino IDE once or twice, to make an LED blink - I mostly work on custom boards and ARM processors.

Also, thanks a lot for providing a fork that is Arduino compatible :)

**Comment by aimass** [comment]
Glad to contribute my $0.02. Great work BTW, the code is nice and elegant seems to be done with a lot of TLC 
People these days have forgotten the “art” of programming. I am happy to have found this lib for my project.
