### ISSUE TITLE
unnecessary change of input?

### ISSUE THREAD

**Issue by monolifed** [kokke/tiny-AES-c#73]
I see in AES_CBC_encrypt_buffer code:  
`XorWithIv(input); memcpy(output, input, BLOCKLEN);`
I was expecting something like: 
`memcpy(output, input, BLOCKLEN); XorWithIv(output);`

**Comment by kokke** [comment]
Hi @monolifed and thanks for reading my code :)

I think you're right. Users might not expect their input buffer's content to be changed.
I'll commit a change to the code.

Thanks for your input :)
