### ISSUE TITLE
Compiling the program

### ISSUE THREAD

**Issue by 22karthik** [kokke/tiny-AES-c#79]
hi,
I am compiling this program in windows machine.Please let me know to how to compile this program
gcc -o aes aes.c gives undefined ref errors

**Comment by DamonHD** [comment]
It is not fair IMHO to ask a package maintainer to teach you how to use generic tools.

**Comment by kokke** [comment]
hi @22karthik 

`gcc -o aes aes.c` will be missing the `main()`-function. Include the `test`-file or write a main-function yourself.

You should be able to get it working by writing `gcc -o aes aes.c test.c`

**Comment by 22karthik** [comment]
Thank you very much this saved my day

**Comment by kokke** [comment]
No problem @22karthik - glad to be able to help :)
