### ISSUE TITLE
Injecting/Testing payload 

### ISSUE THREAD

**Issue by 22karthik** [kokke/tiny-AES-c#81]
Hi,
I am new Data encryption,Please let me know how to inject the payload for "Hi,this is data encryption" how do I encrypt and decrypt in the above code with aes128 and cbc.

Thanks in advance

**Comment by kokke** [comment]
Hi @22karthik 

Please see `test.c` for examples on how to encrypt and decrypt data.
That file demonstrates how to use all the modes of operations and all the key-sizes.

For more resources on encryption and AES specifically, check these resources:

[Block cipher modes of operation @ wikipedia - explains differences between ECB, CBC, CTR etc.](https://en.wikipedia.org/wiki/Block_cipher_mode_of_operation)

[NIST documents containing details about the implementation and test vectors - lots of details](http://nvlpubs.nist.gov/nistpubs/Legacy/SP/nistspecialpublication800-38a.pdf)

[Wikipedias page on AES](https://en.wikipedia.org/wiki/Advanced_Encryption_Standard)
