### ISSUE TITLE
Compatibilty

### ISSUE THREAD

**Issue by RKTRIP** [kokke/tiny-AES-c#84]
Hello Team,

Could you please let me know how much this Tiny AES is compatible with CMAC (Cipher Message Authentication Code) with link give at end, as RFC 4493 of CMAC is calling  using AES_128(X,K,Y) three argument bit different from Tiny AES implementation.

https://tools.ietf.org/html/rfc4493#page-14

Regards

**Comment by kokke** [comment]
Hi @RKTRIP and thanks for your interest :)

I don't know the specifics of CMAC and have only skimmed the RFC.
This library contains all the building blocks you should need to be able to build any AES-based algorithm.

After skimming the RFC, it looks like CMAC is using AES-ECB - which is supported.

**Comment by kokke** [comment]
Hmm I'm not after reading [the wiki page](https://en.wikipedia.org/wiki/One-key_MAC).

However it looks like it's just another sort of mode-of-operation, and I am still certain that this library is compatible.

**Comment by RKTRIP** [comment]
Hello kokke 
Thanks for the reply, I will look into the Tiny-AES again and let you know results.
Regards

**Comment by kokke** [comment]
Hi @RKTRIP - that sounds really interesting :)

I would be very excited to see a CMAC-implementation built with this library.

**Comment by RKTRIP** [comment]
Hello Kokke,

I have changed the Input for ECB encrypt and CBC encrypt as per the standard document as given below FIPS 197.

http://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.197.pdf

Page: Key generation verification at page ---   27,28, match with attachment logfin.txt
          final encrypted message at page ------- 33,34  only ecb_encrypt match but cbc_encrypt output is different.

[logfin.txt](https://github.com/kokke/tiny-AES-c/files/1614590/logfin.txt)
[test.txt](https://github.com/kokke/tiny-AES-c/files/1614591/test.txt)

AS PER FIPS197:
Input = 32 43 f6 a8 88 5a 30 8d 31 31 98 a2 e0 37 07 34
Cipher Key = 2b 7e 15 16 28 ae d2 a6 ab f7 15 88 09 cf 4f 3c
Expected Output = 39 02 dc 19 25 dc 11 6a 84 09 85 0b 1d fb 97 32

Below is output from tiny-AES-Implementation
ECB encrypt: 3925841d02dc09fbdc118597196a0b32
CBC encrypt: e6fc19f8d269588524c00008fb1a572f

Note :- Output from ECB encrypt match with the http://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.197.pdf
But CBC Output is different, How we could compare test vector for CBC encrypt implementation, Is THERE ANY SEPRATE TEST VECTOR TO VERIFY AGAINST CBC OUTPUT, as CBC is using Initial Vector which is not part of FIPS 197 could you please let me know the standard Test Vector to test AES with CBC?
in attachment test.txt is simplified test.c with only ecb_encrypt and cbc_encrypt enabled.

Thanks and Regards

**Comment by RKTRIP** [comment]
Hello Team,

Just now I tested tiny-AES with "cbc_encrypt()" implementation with the test vector provided in RFC 3602:-   https://tools.ietf.org/html/rfc3602#section-4, it got passed.

I already tested Test vector of RFC4493  with the tiny-AES **"ecb_encrypt()"** its passesd but How RFC 4493 could be compatible with the "**cbc_encrypt**" ??? 

So my question is Only about compatibility of https://tools.ietf.org/html/rfc4493#page-14 with tiny-AES cbc_encrypt  ???

Thanks and Regards

**Comment by RKTRIP** [comment]
Hello Team,

Ok, That's solved now, AES_CBC need NULL vector during testing with RFC 4493, Thanks for cooperation.

Thanks and Regards
