### ISSUE TITLE
Decrypting the data

### ISSUE THREAD

**Issue by 22karthik** [kokke/tiny-AES-c#85]
Hi @kokke 

I am at the final stage now.Please help me with the last question I have
 ```C
#include <stdio.h>
#include <string.h>
#include <stdint.h>
#include<stdlib.h>
// Enable ECB, CTR and CBC mode. Note this can be done before including aes.h or at compile-time.
// E.g. with GCC by using the -D flag: gcc -c aes.c -DCBC=0 -DCTR=1 -DECB=1
#define CBC 1
#define CTR 1
#define ECB 1

#include "aes.h"


static uint8_t* decrypt(uint8_t* key,uint8_t* in,int n,int keylen);


static uint8_t* returnbytesfromstring(char bytes[], int nbytes);
   
uint8_t payload[20],returnbytes[20];

int main(void)
{
	//ptr to plaintext conversion
	uint8_t* data;
	//ptr to password conversion
	uint8_t* data1;
	//the plaintext and the password from user
    char plaintext[20],password[20];
    //str length of plaintxt and key
    int plaintextlen,pwdlen;
    //store the pointers vlues and pass these  values to the encrypt functon
    uint8_t in[20],key[20];
	int i=0;
	//encrypted string ptr
	uint8_t* encryptedstrptr;
	//encrypted string
	uint8_t encryptedstr[20];
	
	//character array to eliminate the null character
	char charplaintxt[20],charpassword[20];
	
	//uint8_t key[16] = { 0x2b, 0x7e, 0x15, 0x16, 0x28, 0xae, 0xd2, 0xa6, 0xab, 0xf7, 0x15, 0x88, 0x09, 0xcf, 0x4f, 0x3d };
	
	#ifdef AES128
	    printf("\nTesting AES128\n\n");
	#elif defined(AES192)
	    printf("\nTesting AES192\n\n");
	#elif defined(AES256)
	    printf("\nTesting AES256\n\n");
	#else
	    printf("You need to specify a symbol between AES128, AES192 or AES256. Exiting");
	    return 0;
	#endif

    
    
    printf("enter the string to sent in air\n");
    fgets(plaintext,20,stdin);
    //-1 to eliminate space
    plaintextlen=strlen(plaintext)-1;
    
    //store the string into char array to eliminate null character
    for(i=0;i<plaintextlen;i++)
      charplaintxt[i]=plaintext[i];
      
	//paintext conversion**********************************
	data=returnbytesfromstring(charplaintxt,plaintextlen);
	
    //store the pointer values
	for(i=0;i<plaintextlen;i++)
	  in[i]=*(data+i);
	  
	
	  
	printf("enter pwd to encrypt the string\n");
    fgets(password,20,stdin);
    pwdlen=strlen(password)-1;
    
    //store the string into char array to eliminate null character
    for(i=0;i<pwdlen;i++)
      charpassword[i]=password[i];
      
      
    
    //password conversion*********************************
     data1=returnbytesfromstring(charpassword,pwdlen);
	
    //store the pointer values
	for(i=0;i<pwdlen;i++)
	  key[i]=*(data1+i);
	  
	  
	  
	//pass the key and data and size of data to be encrypted****************************** 
    encryptedstrptr=decrypt(key,in,plaintextlen,pwdlen);
    //store the pointer values
	for(i=0;i<plaintextlen;i++)
	encryptedstr[i]=*(encryptedstrptr+i);
    
	
	printf("the data from encrypt function is:\n");
	//print the obtained data1
	for(i=0;i<plaintextlen;i++)
	
		printf("0x%.2X, ", encryptedstr[i]);
        printf("\n");
	
	
	printf("success");
    
    return 0;
}



//key is pwd

static uint8_t* decrypt(uint8_t* key,uint8_t* in,int plaintxtlen,int keylen)
{
	int i=0;
	//get the values of pointer and assign the pointed values to variable,make payload global variable
	uint8_t secretkey[keylen];
	
	//assign the payload value
	for(i=0;i<plaintxtlen;i++)
	{
	   payload[i]=*(in+i);
	  	
    }
	  
	
	for(i=0;i<keylen;i++)
	{
	   secretkey[i]=*(key+i);
	}
	  
     
    uint8_t iv[16]  = { 0xf0, 0xf1, 0xf2, 0xf3, 0xf4, 0xf5, 0xf6, 0xf7, 0xf8, 0xf9, 0xfa, 0xfb, 0xfc, 0xfd, 0xfe, 0xff };
    
    struct AES_ctx ctx;
   
 
    AES_init_ctx_iv(&ctx, secretkey, iv);
    AES_CTR_xcrypt_buffer(&ctx, payload, plaintxtlen);

   
   
   return payload;
    
    
}


static uint8_t* returnbytesfromstring(char bytes[], int nbytes)
{
   
	int i=0;
        for(i=0;i<nbytes;i++)
	returnbytes[i]=(unsigned char)bytes[i];
	

	for(i=0;i<nbytes;i++)
		
		printf("0x%.2X",returnbytes[i]);
        printf("\n");

	return returnbytes;
}
```

I pass data "encrypt" and password "kar" with hex code 0x65,0x6E,0x63,0x72 ,0x79 ,0x70 ,0x74  and 0x6B,0x61 ,0x72 respectively.

and the encrypted string that I am expecting is 0x19, 0x58, 0x29, 0xC8, 0xA2, 0xBB, 0xF2 but I am getting
0x97, 0xB3, 0x93, 0xEB, 0xE4, 0x18, 0x82

I have verified step by step.I have where things are going wrong.

Thanks in advance

**Comment by kokke** [comment]
@22karthik please don't open any more issues asking me to debug your code.
This is the third issue you open asking me for general assistance.

Why are you expecting that specific output? 

I can't really help you debug the code because I have a hard time understanding what is happening in your code.
I don't understand what `returnbytesfromstring` is needed for.

**Comment by 22karthik** [comment]
So I take in plaintext and key from user, pass it to  returnbytesfromstring and generate corresponding unsigned char array.Collecting these arrays,I pass them to decrypt function.The same function performs encryption and decryption,just I have named it decryption.So,here is the problem in generating the unsigned char array generated after encryption is not same as required.

**Comment by 22karthik** [comment]
Tried debugging the code by printing variables like in and key passed to the decrypt function and everything seems to be correct .
If this is working I am done with this please help me:)

**Comment by 22karthik** [comment]
I need to encrypt and send the data for Lora device.It is iot based project

**Comment by kokke** [comment]
> So I take in plaintext and key from user, pass it to returnbytesfromstring and generate corresponding unsigned char array.Collecting these arrays,I pass them to decrypt function.The same function performs encryption and decryption,just I have named it decryption.So,here is the problem in generating the unsigned char array generated after encryption is not same as required.

I need to see all the code in order to help you.

**Comment by kokke** [comment]
> The returnbytesfromstring function takes in char array and returns a unsigned char hexa decimal array
> 
> For Example,"encrypt"-->0x65,0x6E,0x63,0x72 ,0x79 ,0x70 ,0x74

I don't think I understand. A char array like this:
```C
char char_array[] = { 'e','n','c','r','y','p','t' };
```

is exactly the same as this:
```C
uint8_t u8_array[] = { 0x65,0x6E,0x63,0x72 ,0x79 ,0x70 ,0x74 };
```

The two arrays have the same size and contain the same data.
There is no need to create a function to convert from one to another.

**Comment by kokke** [comment]
You can create an unsigned char array. 
Read signed char's from the user and save them in the unsigned char array by casting every time you save a byte.
You don't need to create an array of signed chars and an array of unsigned chars and use a function to copy around - that only confuses me.

You still haven't told me how you have generated the data you want to verify against.
Because of that, I don't really know what your problem is.
I can copy/paste the code you provide and run it.
That prints out a string and then what?
You tell me you expect something else to be printed out, but why do you expect something different?
I can't help you until you answer that question.

**Comment by 22karthik** [comment]
Hi @kokke 
Thanks for the reply.I agree that the function returnstringbytes is unnecessary.But the encrypted string that is printed is not corresponding string for a given plaintext and key. I checked the parameters passed to the encryption/decryption function everything seems to be right.

**Comment by 22karthik** [comment]
The code that I have shown you is 90% of the code for the module I will just call configuration of the module and pass the encrypted data to the module to be transmitted,it has no dependency on working of this code.

**Comment by 22karthik** [comment]
I just wrote a small function to generate to print hexa byte code for a given string so given key and plaintext.I am able to know hex code.Also from your code .I am able to generate a encrypted array ,which I am able to decrypt.
So the encrypted result is also correct

**Comment by kokke** [comment]
> But the encrypted string that is printed is not corresponding string for a given plaintext and key.

You are still not answering the question. What are you verifying against. Why do you expect something different than what you are getting - how are you comparing the values.

I can't answer the question before you tell me where you get the data you are comparing against.

**Comment by kokke** [comment]
And @22karthik - I'm closing this issue since it's not an issue.
**Please don't open any more issues about your IoT project.**

**Comment by 22karthik** [comment]
I will attach the code

```C
#include <stdio.h>
#include <string.h>
#include <stdint.h>
#include<stdlib.h>
// Enable ECB, CTR and CBC mode. Note this can be done before including aes.h or at compile-time.
// E.g. with GCC by using the -D flag: gcc -c aes.c -DCBC=0 -DCTR=1 -DECB=1
#define CBC 1
#define CTR 1
#define ECB 1

#include "aes.h"


static void test_encrypt_ctr(void);
static void test_decrypt_ctr(void);
static void printhex(const unsigned char *bytes, int nbytes);
static void typeatringtogeneratehex();

int main(void)
{

#ifdef AES128
    printf("\nTesting AES128\n\n");
#elif defined(AES192)
    printf("\nTesting AES192\n\n");
#elif defined(AES256)
    printf("\nTesting AES256\n\n");
#else
    printf("You need to specify a symbol between AES128, AES192 or AES256. Exiting");
    return 0;
#endif

    //decryption/encryption() copy paste the hex code in key and plaintext to see the encrytion/decryption working
    test_decrypt_ctr();
    //generates hex array for a any string
   typeatringtogeneratehex();
    return 0;
}


static void pr_hexbytes(const unsigned char *bytes, int nbytes)
/* Print bytes in hex format + newline */
{
   int i;
   for (i = 0; i <= nbytes; i++)
   	printf("0x%.2X, ", bytes[i]);
   printf("\n");
}

//convert string to bytes
static void typeatringtogeneratehex(){
	
	//give the input data as string
     char data[]="kar";//type any string to generatwe the hex chars
	 
	  char *lpData;
      long nbytes;
      char *lpszCopy;
	 	
      /* Convert string to bytes */

      lpData = (char*)data;
      nbytes = strlen(data);
      printf("printing hex format of encrypt\n");
      pr_hexbytes(lpData, nbytes);

      /* Convert bytes to a zero-terminated string */
	   lpszCopy = malloc(nbytes + 1);
	   memcpy(lpszCopy, lpData, nbytes);
	   lpszCopy[nbytes] = '\0';
	   printf("'%s'\n", lpszCopy);	
    
       free(lpData);
       free(lpszCopy);

}

static void test_xcrypt_ctr(const char* xcrypt);

static void test_decrypt_ctr(void)
{
    test_xcrypt_ctr("decrypt");
}

static void test_xcrypt_ctr(const char* xcrypt)
{
	int n=0,i=0;
	//hex for encrypt 0x65,0x6E,0x63,0x72 ,0x79 ,0x70 ,0x74 
	// 0x19, 0x58, 0x29, 0xC8, 0xA2, 0xBB, 0xF2
	
#ifdef AES128
    uint8_t key[3] = {0x6B,0x61 ,0x72};//kar,type your key here  in hex format
    uint8_t in[7]  = {0x97, 0xB3, 0x93, 0xEB, 0xE4, 0x18, 0x82};//encrypt,type your plaintext here in hex format
#elif defined(AES192)
    uint8_t key[24] = { 0x8e, 0x73, 0xb0, 0xf7, 0xda, 0x0e, 0x64, 0x52, 0xc8, 0x10, 0xf3, 0x2b, 0x80, 0x90, 0x79, 0xe5, 
                        0x62, 0xf8, 0xea, 0xd2, 0x52, 0x2c, 0x6b, 0x7b };
    uint8_t in[64]  = { 0x1a, 0xbc, 0x93, 0x24, 0x17, 0x52, 0x1c, 0xa2, 0x4f, 0x2b, 0x04, 0x59, 0xfe, 0x7e, 0x6e, 0x0b, 
                        0x09, 0x03, 0x39, 0xec, 0x0a, 0xa6, 0xfa, 0xef, 0xd5, 0xcc, 0xc2, 0xc6, 0xf4, 0xce, 0x8e, 0x94, 
                        0x1e, 0x36, 0xb2, 0x6b, 0xd1, 0xeb, 0xc6, 0x70, 0xd1, 0xbd, 0x1d, 0x66, 0x56, 0x20, 0xab, 0xf7, 
                        0x4f, 0x78, 0xa7, 0xf6, 0xd2, 0x98, 0x09, 0x58, 0x5a, 0x97, 0xda, 0xec, 0x58, 0xc6, 0xb0, 0x50 };
#elif defined(AES256)
    uint8_t key[32] = { 0x60, 0x3d, 0xeb, 0x10, 0x15, 0xca, 0x71, 0xbe, 0x2b, 0x73, 0xae, 0xf0, 0x85, 0x7d, 0x77, 0x81,
                        0x1f, 0x35, 0x2c, 0x07, 0x3b, 0x61, 0x08, 0xd7, 0x2d, 0x98, 0x10, 0xa3, 0x09, 0x14, 0xdf, 0xf4 };
    uint8_t in[64]  = { 0x60, 0x1e, 0xc3, 0x13, 0x77, 0x57, 0x89, 0xa5, 0xb7, 0xa7, 0xf5, 0x04, 0xbb, 0xf3, 0xd2, 0x28, 
                        0xf4, 0x43, 0xe3, 0xca, 0x4d, 0x62, 0xb5, 0x9a, 0xca, 0x84, 0xe9, 0x90, 0xca, 0xca, 0xf5, 0xc5, 
                        0x2b, 0x09, 0x30, 0xda, 0xa2, 0x3d, 0xe9, 0x4c, 0xe8, 0x70, 0x17, 0xba, 0x2d, 0x84, 0x98, 0x8d, 
                        0xdf, 0xc9, 0xc5, 0x8d, 0xb6, 0x7a, 0xad, 0xa6, 0x13, 0xc2, 0xdd, 0x08, 0x45, 0x79, 0x41, 0xa6 };
#endif
    uint8_t iv[16]  = { 0xf0, 0xf1, 0xf2, 0xf3, 0xf4, 0xf5, 0xf6, 0xf7, 0xf8, 0xf9, 0xfa, 0xfb, 0xfc, 0xfd, 0xfe, 0xff };
    uint8_t out[64] = { 0x6b, 0xc1, 0xbe, 0xe2, 0x2e, 0x40, 0x9f, 0x96, 0xe9, 0x3d, 0x7e, 0x11, 0x73, 0x93, 0x17, 0x2a,
                        0xae, 0x2d, 0x8a, 0x57, 0x1e, 0x03, 0xac, 0x9c, 0x9e, 0xb7, 0x6f, 0xac, 0x45, 0xaf, 0x8e, 0x51,
                        0x30, 0xc8, 0x1c, 0x46, 0xa3, 0x5c, 0xe4, 0x11, 0xe5, 0xfb, 0xc1, 0x19, 0x1a, 0x0a, 0x52, 0xef,
                        0xf6, 0x9f, 0x24, 0x45, 0xdf, 0x4f, 0x9b, 0x17, 0xad, 0x2b, 0x41, 0x7b, 0xe6, 0x6c, 0x37, 0x10 };
    struct AES_ctx ctx;
    
    AES_init_ctx_iv(&ctx, key, iv);
    AES_CTR_xcrypt_buffer(&ctx, in, 7);
    
    //pass the in[] which contains the encrypted/decrypted string
    
   n=sizeof(in);
   printf("size of in %d",n);
   
  
   char * data;
   data=malloc(n);
   data=(char *)in;
   pr_hexbytes(data,n);
   //data[n+1]='\0';
   printf("'%s'",data);
   
   
    
    
}






```

**Comment by 22karthik** [comment]
Hi
Iam not professional coding .But I have used all my effort to get this code compiling but still the output is not as required.I will try my best to resolve the issue.Thanks for your understanding.
Take your time to reply:)

**Comment by kokke** [comment]
@22karthik the program crashes when I compile you code and run it. I'm not sure I know what to do in order to help you.

**Comment by DamonHD** [comment]
In other venues I see this sort of interaction when someone is trying to get their class homework done for free on the Internet.

Using the issues feature of a public repo is really not the appropriate place to learn basic programming skills IMHO.

Rgds

Damon

**Comment by 22karthik** [comment]
Thank you for helping me :)

**Comment by 22karthik** [comment]
Thank you @kokke for the help,thank you

**Comment by 22karthik** [comment]
Hi @kokke 

Thanks for the help,I was abe to solve the problem by choosing right size of key.But please how did you generate the IV and why did you use the particular IV 
uint8_t iv[16]  = { 0xf0, 0xf1, 0xf2, 0xf3, 0xf4, 0xf5, 0xf6, 0xf7, 0xf8, 0xf9, 0xfa, 0xfb, 0xfc, 0xfd, 0xfe, 0xff };

**Comment by 22karthik** [comment]
can I just randomly use any IV for the program and what is its purpose.I read the documentation.But understand clearly.If can tell me briefly it will be helpful.

**Comment by kokke** [comment]
The input text, IV, key etc. used in `test.c` are taken from the test vectors in http://nvlpubs.nist.gov/nistpubs/Legacy/SP/nistspecialpublication800-38a.pdf

In other words, the reason for using these specific values is to be able to check and verify the implementation.

IVs can be chosen randomly but the IV is not secret, only the key is.

The purpose of the IV is basically to add some extra entropy / 'randomness'.

There are lots of answers on crypto.stackexchange and stackoverflow.com that can help you learn more about block ciphers. These for example:

https://crypto.stackexchange.com/questions/3965/what-is-the-main-difference-between-a-key-an-iv-and-a-nonce

https://stackoverflow.com/questions/9049789/aes-encryption-key-versus-iv

Be aware that using an IV with the same key more than once will leak information, so you should always strive to never re-use an IV.

**Comment by kokke** [comment]
This page has more info regarding recommended IV uses in CBC mode:
https://defuse.ca/cbcmodeiv.htm

**Comment by 22karthik** [comment]
Thank you @kokke :)

**Comment by kokke** [comment]
A side note:
I can recommend Bruce Schneier's book "Cryptography Engineering".
https://www.schneier.com/books/cryptography_engineering/

In my humble opinion it isn't overly theoretical but still explains the topic rigorously.

**Comment by 22karthik** [comment]
Hi @kokke 
Is it possible to decrypt the encrypted string(AES-128-CTR) in php using openssl_decrypt function.Do any information about this,please let me know.
Thank you

**Comment by kokke** [comment]
Hi @22karthik - I don't know about PHP, but I've successfully used python together with this library. Any comformant implementation should work, regardless of language.

**Comment by 22karthik** [comment]
@Kokke
Thank you :)

**Comment by innoveratech** [comment]
cause of 0x00, null character. I had a same problem. I removed 0(zero)  from  key, iv.  it's work
