### ISSUE TITLE
aes.hpp superfluous - C++/C has standards support semantics not used

### ISSUE THREAD

**Issue by ascheurer** [kokke/tiny-AES-c#87]
've seen a lot of changes over the last few months and many positive - increased attention to FIPS compliance which is very important to my intended efforts w/ AES256 standards compliance/interoperability with FPGA/PL implementations of AES256 standard and other implementations - very important to adhere to standards.

However the use of aes.hpp does not follow a standard support of C++ and C usages.

Currently aes.hpp contains:
#ifndef AES_HPP
#define AES_HPP

#ifndef __cplusplus
#error Do not include the hpp header in a c project!
#endif //__cplusplus

extern "C" {
#include "aes.h"
}

#endif //AES_HPP

and no issue with using aes.hpp to imply C++ as boost does where .hpp means C++ and this is fine. However this is used for C++ code that includes C++ keywords like class, private, etc... basically class definitions that if used in a .c module would look out of place - its .hpp so it goes with .cpp

However aes.hpp is not correct usage.

aes.h needs to have function prototypes only - not preprocessor symbols or structs - these are common in C and C++ but only function prototypes to use the __cplusplus reserved pre-processor symbol for C++ but not recognized in C.

Furthermore using prepended and post underscores is not necessary and does not comply w/ the standard as the use of _ with preprocessor symbols is reserved by the compiler - eg. TIME but also other symbols

#ifndef AES_H
#define AES_H

needs only be AES_H

aes.h to be compliant with C/C++ interoperability standards (ANSI C and C99) would be

#ifndef AES_H
#define AES_H
...
#ifdef __cplusplus
extern "C" {
#endif

/* function prototypes only ... /
void AES_ECB_encrypt(struct AES_ctx ctx, const uint8_t* buf);
...

#ifdef __cplusplus
}
#endif

Now this is usable by C and C++ transparently - aes.hpp does not need to be used at all unless you do want to create a C++ wrapper in aes.hpp and that would make sense for those C++ folks that want a class interface w/ private data encapsulating context etc...

its significantly better to support transparent usage than issue an #error from the preprocessor when a C module includes a .hpp file ...
if the .hpp includes a class keyword it will be flagged as an error in any case.

One could also an error in the .hpp as you've done if a C module includes it ... however it shouldn't be necessary for a C++ program to use a .hpp file if they only want the C functions to be extern "C" -- compilers do this with all the standard C library functions like strcpy, memcpy etc... where a C++ program can include stdlib.h without having to use or any other non-C++ include - C includes must use the above method to be usable transparently by C and C++ programs.

aes.h as it currently standards is not compliant to standard C and C++ usage.

aes.hpp currently is not needed but harmless if left as is but would simply wrap aes.h and the #error if left there could stand if aes.hpp accidently used in  a C module.

The other issue is that C99 types are okay - many compilers are not C99 compliant but can be made to support uintxx_t and intxx_t etc... however may consider removing C++ comments such as // /and declaring variables anywhere within a function - this is C99 and C++ supported but not ANSI C - ANSI C 89/90 would allow portability to more compilers. Diab, Microsoft - many compilers still do not support C99.

I can help out w/ these compiler portability concerns if my efforts are needed.

**Comment by ascheurer** [comment]
consider changing all comments to /* style */ which is also supported in C++ and declare variables at the top of the function or if you want to declare a variable at the point of usage use this technique in ANSI C 89/90
void function(void)
{

{ /* create scope for local variable w/ in function */
    int local; 
} /* end scope */

}

in addition I do see your prototypes using static void test_encrypt_cbc(void); and not 
static void test_encrypt_cbc(); which is quite different --- you can also use (void) in C++ as well - its entirely optional.

**Comment by kokke** [comment]
Hi @ascheurer and thanks for your contribution.

You are proposing a lot of changes, some of which I can understand and some of them not.

Please consider opening pull requests actioning the changes you wish to see - preferably one at a time :) 

That way I can see what you mean concretely and review the changes one at a time.

It's not that I don't find your input constructive, I just find the other way more effective time-wise on my end. It usually also means you get to decide changes if you make them and send me a PR :)
As long as the changes doesn't adds bloat or changes the scope of the project, I usually accept them.

I will close this issue for now, but we can continue the discussion if you want :)

**Comment by ascheurer** [comment]
Sure I can clarify better through making changes in the source code and showing - really they are very simple improvements that are innocuous and have no effect on the size or performance. 
Really not a lot of changes 
1.) The C++ compatibility of the aes.h - thats an easy one … very simple and follows the rules of any compiler out there with regard to C++ and C linkage.

2.) On the API you clarified that … I do have a workaround for it at least avoiding calling the init for every encrypt/decrypt— the init is called once and have to manage 2 copies and encapsulate that - very threadsafe as well.  I’ll provide code for that example and it may be that the way you have it is okay. 

3.) On ANSI C 89/90 - well not all compilers these days are C99 - in fact most of them are not - they are either ANSI C 89/90 and C++ 98 or they support later versions of C++ and maybe C99 - re: comments etc… and using gcc -ansi -std=c90 fails because of minor things that have no impact on the code footprint or performance. The objective here is to support as many compilers as you can - simply portability. 

I can provide concreteness in providing source code updates. 
I’m using the latest version - good that multi-threading was addressed as I was given the old version by another developer. 
Agreed that discussion does reach an end point and demonstrations with code is warranted. 

Regards,
Andrew Scheurer
