### ISSUE TITLE
Out of array bounds for data lengths that arent multiplications of aes block size, despite buffers being multiplications

### ISSUE THREAD

**Issue by Wolowin** [kokke/tiny-AES-c#88]
Hey,

There is a bug in encrypt/decrypt loop that iterates over data for (length % BLOCKLEN ) != 0, causing buffer overrun even for buffers being multiplication of BLOCKLEN .
For data: BLOCKLEN = 16, length = 31, input[32], output[32].
	for (i = 0; i < length; i += BLOCKLEN)
	{
           (...)
		input += BLOCKLEN;
		output += BLOCKLEN;
	}
the ending condition causes loop to run twice instead of just once, which increments input and output past its last element. This way the operations in the "if (extra)" brackets will cause a buffer overrun
	if (extra) 
	{
		CRuntimeFunction(memcpy(output, input, extra));
		state = (state_t*)output;
		Cipher(); //crash
	}

The issue can be fixed by for changing the "for" loop ending condition to:
	const int lengthWithoutExtra = length - extra;
	for (i = 0; i < lengthWithoutExtra; i += BLOCKLEN)

**Comment by kokke** [comment]
Hi @Wolowin and thanks for taking an interest in this project :)

If I understand you correctly, this issue is already mentioned in the README:

> No padding is provided so for CBC and ECB all buffers should be mutiples of 16 bytes. For padding PKCS7 is recommendable.
> There is no built-in error checking or protection from out-of-bounds memory access errors as a result of malicious input.

You should pad you inputs so that the length is a multiple of 16 bytes.

**Comment by Wolowin** [comment]
Hmm I understood from this line that buffers need to allocate the size that is multiplication of 16, but the length itself can be different. The presence of variable extra
`uint8_t extra = length % BLOCKLEN; /* Remaining bytes in the last non-full block */`
in the source code further convinced me that this is right.

**Comment by Wolowin** [comment]
Sorry if I talk nonsense - I'm at the beginning of my journey when it comes to cryptography. However if not-full-sized last block isn't supported then I believe the "if (extra) {" bracket should be removed. Then the padding of last block will be whatever data (or junk) the user puts as the last bytes of the input buffer. 

The if(extra) bracket was also missing xoring with IV if I understand the algorithm correctly

**Comment by kokke** [comment]
I agree that the README-text and the comment are ambiguous now that I read it again.
I will re-think new formulations.

In general, the block ciphers work with blocks of different length, in contrast to stream ciphers.
CTR-mode transforms a block cipher to a stream cipher, so if you don't want to mess with padding, consider using CTR instead.

Wikipedia has a nice explanation of the different modes of operation.
https://en.wikipedia.org/wiki/Block_cipher_mode_of_operation

**Comment by kokke** [comment]
This issue has been raised numerous times by others throughout the years.
Apparently I am not good at explaining how to use the code :)

**Comment by Wolowin** [comment]
Hmm I actually think I have been using an old revision and that extra part is already gone. Sorry for the trouble ;p

I would also like to thank you for making this lib. It's been a lot of help in one of my recent projects

**Comment by kokke** [comment]
@Wolowin I'm really glad to hear that you have found use for the library :) 

I am always excited to hear from users of my code. It gives me a warm fuzzy feeling to know that others have found the code useful :D

I wrote the code initially because I needed AES on a 8-bit microprocessor, but could not find any implementations small enough to fit.

The `extra`-bit is indeed gone. @sdrsdr made a huge refactoring effort in #75 + #76 that removed the faulty handling of `extra` bytes :)

**Comment by Wolowin** [comment]
Yeah I see. He did a good job indeed. I forked the project and wanted to do just the same - remove global / static variables for thread safety and deal with the extra. But I checked out the repo with newest changes and I noticed the content is different than what I was used to ;p

Gotta get newest change set then ;p
