### ISSUE TITLE
AES Encryption / Decryption in Arduino IDE for ESP8266 

### ISSUE THREAD

**Issue by syeedhaiderali** [kokke/tiny-AES-c#92]
I want to encrypt / decrypt data coming from mobile. Can you please guide me how can I encrypt / decrypt this data in Arduino IDE for ESP8266. Using your program, as there are 2 programs aes.c and test.c.

**Comment by DamonHD** [comment]
IMHO this is a large programming question which it is not reasonable to ask the project maintainer to solve for you.

Rgds

Damon

**Comment by kokke** [comment]
Hi @syeedhaiderali 

`test.c` exercises the code in `aes.c`, which has an interface described in `aes.h`.
What is provided in `test.c` should be enough in itself to demonstrate all of the functionality.

I have to agree with @DamonHD on this one. I will not provide a guide for you on how to encrypt / decrypt data from a mobile app. Stackoverflow.com is much better suited for those types of questions.

If you have specific questions regarding the implementation, I will gladly help, but I will not provide guides on how to build applications using this library.

The "Issues"-section on Github should be reserved for bug-reports and technical questions.
