### ISSUE TITLE
Padding needed?

### ISSUE THREAD

**Issue by Granyy** [kokke/tiny-AES-c#93]
Hello!

Thank you for work on this project! It works great!

Nevertheless, I do have a question about the code: **Is padding really needed?**
I've run some tests with or without padding and I got the same result. In both case, it works really fine. Therefore, what's the danger to encrypt without using any padding methods?

Thank you for your response.
Leo

**Comment by kokke** [comment]
Hi @Granyy and thanks for the kind words :)

What kind of padding are you referring to? Value-wise or size-wise?

If you are using CBC or ECB-mode, your buffers need to be a multiple of 16 bytes, or the code will read beyond the allocated space - i.e. doing invalid memory accesses.

Value-wise, the padding is needed for added security, as it makes some types of cryptanalysis harder. The algorithm will work though without padding, as long as both ends assume the same default-values (e.g 0), but there is some loss of security.

You can read up on the justifications for padding on wikipedia or http://crypto.stackexchange.com/ :)

**Comment by Granyy** [comment]
I was referring to value-wise padding. Now I've read your response, it makes sense that there is more security when a pad is added.
About your code, _if you don't use padding,_ when you call AES_CBC_encrypt_buffer(struct AES_ctx *ctx,uint8_t* buf, uint32_t length), length **HAS** to be a multiple of 16 bytes then?

Thank you for your response.
Leo

**Comment by kokke** [comment]
Yes, using CBC and ECB requires the buffer-length to be a multiple of 16 bytes :)

**Comment by Granyy** [comment]
Thank you for your response :+1:
