### ISSUE TITLE
CBC encrypt and decrypt issue?

### ISSUE THREAD

**Issue by mp1609** [kokke/tiny-AES-c#95]
Hello there,

I hate to ask such a silly question, but did I miss something to use the AES CBC encryption?

I am using AES128 CBC encryption and modified the main() of "test.c" as follows:

`
int main(void)
{

#ifdef AES128
    printf("\nTesting AES128\n\n");
#elif defined(AES192)
    printf("\nTesting AES192\n\n");
#elif defined(AES256)
    printf("\nTesting AES256\n\n");
#else
    printf("You need to specify a symbol between AES128, AES192 or AES256. Exiting");
    return 0;
#endif	
       //test_encrypt_cbc();
	//test_decrypt_cbc();
	//test_encrypt_ctr();
	//test_decrypt_ctr();
	//test_decrypt_ecb();
    //test_encrypt_ecb();
    //test_encrypt_ecb_verbose();
	//test_encrypt_ecb_verbose();

	uint8_t iv[] = { 0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0a, 0x0b, 0x0c, 0x0d, 0x0e, 0x0f };

	uint8_t i, buf[64], buf2[64];

	// 128bit key
	uint8_t key[16] = { (uint8_t)0x2b, (uint8_t)0x7e, (uint8_t)0x15, (uint8_t)0x16, (uint8_t)0x28, (uint8_t)0xae, (uint8_t)0xd2, (uint8_t)0xa6, (uint8_t)0xab, (uint8_t)0xf7, (uint8_t)0x15, (uint8_t)0x88, (uint8_t)0x09, (uint8_t)0xcf, (uint8_t)0x4f, (uint8_t)0x3c };
	
	// 512bit text
	uint8_t plain_text[64] = { (uint8_t)0x6b, (uint8_t)0xc1, (uint8_t)0xbe, (uint8_t)0xe2, (uint8_t)0x2e, (uint8_t)0x40, (uint8_t)0x9f, (uint8_t)0x96, (uint8_t)0xe9, (uint8_t)0x3d, (uint8_t)0x7e, (uint8_t)0x11, (uint8_t)0x73, (uint8_t)0x93, (uint8_t)0x17, (uint8_t)0x2a,
		(uint8_t)0xae, (uint8_t)0x2d, (uint8_t)0x8a, (uint8_t)0x57, (uint8_t)0x1e, (uint8_t)0x03, (uint8_t)0xac, (uint8_t)0x9c, (uint8_t)0x9e, (uint8_t)0xb7, (uint8_t)0x6f, (uint8_t)0xac, (uint8_t)0x45, (uint8_t)0xaf, (uint8_t)0x8e, (uint8_t)0x51,
		(uint8_t)0x30, (uint8_t)0xc8, (uint8_t)0x1c, (uint8_t)0x46, (uint8_t)0xa3, (uint8_t)0x5c, (uint8_t)0xe4, (uint8_t)0x11, (uint8_t)0xe5, (uint8_t)0xfb, (uint8_t)0xc1, (uint8_t)0x19, (uint8_t)0x1a, (uint8_t)0x0a, (uint8_t)0x52, (uint8_t)0xef,
		(uint8_t)0xf6, (uint8_t)0x9f, (uint8_t)0x24, (uint8_t)0x45, (uint8_t)0xdf, (uint8_t)0x4f, (uint8_t)0x9b, (uint8_t)0x17, (uint8_t)0xad, (uint8_t)0x2b, (uint8_t)0x41, (uint8_t)0x7b, (uint8_t)0xe6, (uint8_t)0x6c, (uint8_t)0x37, (uint8_t)0x10 };

	memset(buf, 0, 64);
	memset(buf2, 0, 64);

	// print text to encrypt, key and IV
	printf("CBC encrypt test:\n\n");
	printf("plain text:\n \n \n");

	for (i = 0; i < 4; ++i)
	{
		phex(plain_text + (i * 16));
	}

	struct AES_ctx ctx;	
	
	AES_init_ctx_iv(&ctx, key, iv);

	uint8_t encypted_text[128];

	printf("\n \n \n");
	printf("encrypted and  decrypted text:\n \n \n");
	for (i = 0; i < 4; ++i)
	{	
		//AES_init_ctx_iv(&ctx, key, iv);				// <<<< UNCOMMENT this line -> working
		AES_CBC_encrypt_buffer(&ctx, plain_text + (i * 16), 32);		
		
		//AES_init_ctx_iv(&ctx, key, iv);				// <<<< UNCOMMENT this line -> working
		AES_CBC_decrypt_buffer(&ctx, plain_text + (i * 16), 32);
		phex(plain_text + (i * 16));
	}
	printf("\n");

    return 0;
}`

The problem is that the text which was encrypted and then decrypted isn't identical to the plain text.
For now, I figured out, that I have to call "AES_init_ctx_iv" before each encrypt / decrypt function call. Can someone confirm this as an issue? Or am I doing something wrong?!

**Comment by kokke** [comment]
Hi @mp1609 and sorry for the slow answer - I am quite busy at the time being.

It doesn't look right that you are encrypting and decrypting at the same time.

I would expect that to ruin the IV since two "sessions" are now using and updating it.

Pull the call to AES_CBC_decrypt_buffer out of the loop, so you have two loops: one encrypting and one decrypting.

**Comment by mp1609** [comment]
Hi kokke, thanks for your response.
Okay I tried what you said and took the AES_CBC_decrypt_buffer into another loop, but unfortunatelly the decrypted text doesn't match the source text. I've zipped my project and attached it here. I only modified the main() in test.c

[tinyAES_exe.zip](https://github.com/kokke/tiny-AES-c/files/1888664/tinyAES_exe.zip)

So the current outpoot looks like this:

```
plain text:


6bc1bee22e409f96e93d7e117393172a
ae2d8a571e03ac9c9eb76fac45af8e51
30c81c46a35ce411e5fbc1191a0a52ef
f69f2445df4f9b17ad2b417be66c3710



encrypted text:


7649abac8119b246cee98e9b12e9197d
7df76b0c1ab899b33e42f047b91b546f
7df76b0c1ab899b33e42f047b91b546f
7df76b0c1ab899b33e42f047b91b546f




decrypted text:


1997ac7bf0198500f69b2102a9732a13
1637d7ed30fd0022df76845dc6854d4a
1637d7ed30fd0022df76845dc6854d4a
1637d7ed30fd0022df76845dc6854d4a
```

**Comment by dwinant** [comment]
@mp1609 try re-initializing the IV from the same source between the encryption and decryption loops

**Comment by mp1609** [comment]
@dwinant Thanks, but the issue remains the same:
Tried following:
```
int main(void)
{

#ifdef AES128
    printf("\nTesting AES128\n\n");
#elif defined(AES192)
    printf("\nTesting AES192\n\n");
#elif defined(AES256)
    printf("\nTesting AES256\n\n");
#else
    printf("You need to specify a symbol between AES128, AES192 or AES256. Exiting");
    return 0;
#endif

	//test_encrypt_cbc();
	//test_decrypt_cbc();
	//test_encrypt_ctr();
	//test_decrypt_ctr();
	//test_decrypt_ecb();
    //test_encrypt_ecb();
    //test_encrypt_ecb_verbose();
	//test_encrypt_ecb_verbose();


	uint8_t iv[] = { 0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0a, 0x0b, 0x0c, 0x0d, 0x0e, 0x0f };

	uint8_t i, buf[64], buf2[64];

	// 128bit key
	uint8_t key[16] = { (uint8_t)0x2b, (uint8_t)0x7e, (uint8_t)0x15, (uint8_t)0x16, (uint8_t)0x28, (uint8_t)0xae, (uint8_t)0xd2, (uint8_t)0xa6, (uint8_t)0xab, (uint8_t)0xf7, (uint8_t)0x15, (uint8_t)0x88, (uint8_t)0x09, (uint8_t)0xcf, (uint8_t)0x4f, (uint8_t)0x3c };
	
	// 512bit text
	uint8_t plain_text[64] = { (uint8_t)0x6b, (uint8_t)0xc1, (uint8_t)0xbe, (uint8_t)0xe2, (uint8_t)0x2e, (uint8_t)0x40, (uint8_t)0x9f, (uint8_t)0x96, (uint8_t)0xe9, (uint8_t)0x3d, (uint8_t)0x7e, (uint8_t)0x11, (uint8_t)0x73, (uint8_t)0x93, (uint8_t)0x17, (uint8_t)0x2a,
		(uint8_t)0xae, (uint8_t)0x2d, (uint8_t)0x8a, (uint8_t)0x57, (uint8_t)0x1e, (uint8_t)0x03, (uint8_t)0xac, (uint8_t)0x9c, (uint8_t)0x9e, (uint8_t)0xb7, (uint8_t)0x6f, (uint8_t)0xac, (uint8_t)0x45, (uint8_t)0xaf, (uint8_t)0x8e, (uint8_t)0x51,
		(uint8_t)0x30, (uint8_t)0xc8, (uint8_t)0x1c, (uint8_t)0x46, (uint8_t)0xa3, (uint8_t)0x5c, (uint8_t)0xe4, (uint8_t)0x11, (uint8_t)0xe5, (uint8_t)0xfb, (uint8_t)0xc1, (uint8_t)0x19, (uint8_t)0x1a, (uint8_t)0x0a, (uint8_t)0x52, (uint8_t)0xef,
		(uint8_t)0xf6, (uint8_t)0x9f, (uint8_t)0x24, (uint8_t)0x45, (uint8_t)0xdf, (uint8_t)0x4f, (uint8_t)0x9b, (uint8_t)0x17, (uint8_t)0xad, (uint8_t)0x2b, (uint8_t)0x41, (uint8_t)0x7b, (uint8_t)0xe6, (uint8_t)0x6c, (uint8_t)0x37, (uint8_t)0x10 };

	memset(buf, 0, 64);
	memset(buf2, 0, 64);

	// print text to encrypt, key and IV
	printf("CBC encrypt test:\n\n");
	printf("plain text:\n \n \n");

	for (i = 0; i < 4; ++i)
	{
		phex(plain_text + (i * 16));
	}

	struct AES_ctx ctx;	
	
	AES_init_ctx_iv(&ctx, key, iv);


	uint8_t encypted_text[128];

	AES_init_ctx_iv(&ctx, key, iv);
	printf("\n \n \n");
	printf("encrypted text:\n \n \n");
	for (i = 0; i < 4; ++i)
	{			
		AES_CBC_encrypt_buffer(&ctx, plain_text + (i * 16), 32);					
		phex(plain_text + (i * 16));
	}
	printf("\n");

	// print text to decrypt
	printf("\n \n \n");
	printf("decrypted text:\n \n \n");

	AES_init_ctx_iv(&ctx, key, iv);
	for (i = 0; i < 4; ++i)
	{		
		AES_CBC_decrypt_buffer(&ctx, plain_text + (i * 16), 32);
		phex(plain_text + (i * 16));
	}
	printf("\n");

    return 0;
}
```

> plain text:


6bc1bee22e409f96e93d7e117393172a
ae2d8a571e03ac9c9eb76fac45af8e51
30c81c46a35ce411e5fbc1191a0a52ef
f69f2445df4f9b17ad2b417be66c3710



encrypted text:


7649abac8119b246cee98e9b12e9197d
7df76b0c1ab899b33e42f047b91b546f
7df76b0c1ab899b33e42f047b91b546f
7df76b0c1ab899b33e42f047b91b546f




decrypted text:


1004fcc386ad013eac8a9dde1506041f
69e216649fedbac3040cfa4e6aec8f47
6df295cc98109e8a9ac16792a0105e7f
69e216649fedbac3040cfa4e6aec8f47

**Comment by dwinant** [comment]
@mp1609 I think you need to change the length parameter from 32 to 16 in your loops.  With a length of 32 it is encrypting most of your data twice, plus touching data past the end of your plain_text array.

When I made that change, in addition to resetting the IV before the decryption, your code ran and gave the correct decrypted text.

**Comment by mp1609** [comment]
@dwinant : Thanks for your answer and also for this cool support!
That worked for me, have a nice weekend.

**Comment by kokke** [comment]
Thank you very much @dwinant for helping closing this issue :) Very much appreciated.

Have a nice weekend.

**Comment by Mohammedyasein** [comment]
i got error when i try to compile test.c is there any documentation for this library .
