### ISSUE TITLE
Code does not verify with Java

### ISSUE THREAD

**Issue by davinci26** [kokke/tiny-AES-c#96]
Hey,

I am using this code to encrypt a message and check if the encrypted message is the same with http://www.devglan.com/online-tools/aes-encryption-decryption. I observe that the values are wrong. Is this expected behavior?

``` C++
    // 128bit key
    uint8_t key[] =        { 0x7a, 0x41, 0x63, 0x6b,
                             0x7a, 0x41, 0x63, 0x6b,
                             0x7a, 0x41, 0x63, 0x6b,
                             0x7a, 0x41, 0x63, 0x6b};
   
    uint8_t  msg[]  = {0x31,0x32,0x33,0x34 };
    struct AES_ctx ctx;

    AES_init_ctx(&ctx, key);
    AES_ECB_encrypt(&ctx, msg);

    printf("ECB encrypt: ");

    for (int i=0;i<16;i++){
        printf("%.2x ",msg[i]);
    }
    printf("\n");

```

**Comment by kokke** [comment]
Hi @davinci26 and thanks for checking out te project.

The test vectors are taken from the NIST standard that defines the algoritm and are thus by definition correct. If a third party does not produce the same output, either the third party implementation is wrong or, more likely, there is some usage confusion. 

It is a common mistake to mixup ASCII encoded text with raw binary. Your linked page also accept base64 encoded input, so I would suspect the second option: usage error.

**Comment by davinci26** [comment]
Hey @kokke . Thanks for the reply.
From what I observed the default tuning for this library is with 0 padding. Is this correct?
I managed to make it work if I specify it like this in Java.

**Comment by kokke** [comment]
Hi @davinci26 - Yes zero padding works well. As stated in the project README: 

"No padding is provided so for CBC and ECB all buffers should be mutiples of 16 bytes. For padding PKCS7 is recommendable."

You can avoid padding if you use CTR mode instead :)

**Comment by kokke** [comment]
@davinci26 if you have gotten the answers you came for, I will close the issue. If not, please let me know :)
