### ISSUE TITLE
CTR mode IV updating

### ISSUE THREAD

**Issue by tanyax** [kokke/tiny-AES-c#98]
Hi, just had a small question. Does the CTR mode still not update the IV? A commit by @nickaknudson mentions that it's lacking this feature. Wouldn't that defeat the purpose of using the CTR mode? However, in the code for `AES_CTR_xcrypt_buffer` I see the IV being incremented. So, I'm not sure what is lacking in the feature.

**Comment by nickaknudson** [comment]
CTR mode is working properly. The counter is updated every block per the specification. 

Depending on your application, you may need the ability to change the counter. This is often referred to as setting a nonce. There is no single defined way to do this, so adding the ability to set the entire counter is necessary.

**Comment by kokke** [comment]
> There is no single defined way to do this, so adding the ability to set the entire counter is necessary.

Was necessary, but is not anymore after PR https://github.com/kokke/tiny-AES-c/pull/89
The last commit by @nickaknudson added that functionality to CTR-mode also - thank you again :)

Sorry for being a bit pedantic, just trying to minimize potential misunderstandings.
